#!/usr/bin/env python3
"""Create cats.json with 380+ facts about cats."""
import json

facts = [
    # === BREED PROFILES ===
    {"text": "The Domestic Shorthair is the most common cat in the world — not a recognized breed, they're mixed-breed cats with short coats."},
    {"text": "Persian cats have been bred since the 1600s and are known for their flat faces, long coats, and calm temperament — they're one of the oldest recognized breeds."},
    {"text": "Maine Coons are the largest domesticated cat breed, with males weighing up to 25 pounds — they're often called 'gentle giants.'", "type": "did-you-know"},
    {"text": "Siamese cats are one of the oldest recognized Asian breeds, originating in Thailand (formerly Siam) and appearing in manuscripts from the 14th century."},
    {"text": "The Ragdoll was created in the 1960s in California by Ann Baker — they go limp like a ragdoll when picked up, hence the name."},
    {"text": "Bengal cats are a hybrid breed created by crossing domestic cats with Asian Leopard Cats, giving them their distinctive wild-looking spotted coat."},
    {"text": "The British Shorthair is one of the oldest English cat breeds and was the inspiration for the Cheshire Cat in Alice in Wonderland.", "type": "did-you-know"},
    {"text": "Abyssinian cats are one of the oldest known breeds, possibly originating in Ethiopia (formerly Abyssinia). They have a distinctive ticked tabby coat."},
    {"text": "The Sphynx cat appears hairless but actually has a fine layer of peach-fuzz fur — the breed originated in Toronto, Canada, in 1966."},
    {"text": "Scottish Fold cats have unique folded ears caused by a genetic mutation discovered in a Scottish barn cat named Susie in 1961."},
    {"text": "Russian Blue cats have a distinctive double coat with a plush, silver-tipped blue-gray color and striking green eyes."},
    {"text": "The Norwegian Forest Cat (Skogkatt) evolved naturally in Scandinavia and features in Norse mythology — they may have traveled with Vikings.", "type": "did-you-know"},
    {"text": "Burmese cats descend from a single cat named Wong Mau, brought from Burma to the US by Dr. Joseph Thompson in 1930."},
    {"text": "The Birman, also called the 'Sacred Cat of Burma,' has a legend claiming its golden coat and blue eyes came from a temple goddess."},
    {"text": "The Oriental Shorthair comes in over 300 color and pattern combinations — more than any other cat breed."},
    {"text": "Devon Rex cats have unusual curly coats, large ears, and pixie-like faces — they're often called 'poodle cats.'"},
    {"text": "The Savannah cat is a hybrid of a domestic cat and Serval (African wildcat) — the largest Savannahs can reach 25 lbs and jump 8 feet high.", "type": "did-you-know"},
    {"text": "Turkish Angora cats are one of the oldest natural breeds, originating in central Turkey — they were once used to breed the Persian."},
    {"text": "The Exotic Shorthair was developed as a short-haired version of the Persian and is sometimes called the 'lazy person's Persian.'"},
    {"text": "Tonkinese cats are a cross between Siamese and Burmese, combining the best traits of both breeds."},
    {"text": "The Cornish Rex has an unusual wavy coat consisting only of the soft undercoat — it originated in Cornwall, England, in the 1950s."},
    {"text": "American Shorthair cats arrived in North America on the Mayflower, brought along to control rats on the ship.", "type": "did-you-know"},
    {"text": "The Manx cat is famous for being tailless — the genetic mutation originated on the Isle of Man in the Irish Sea."},
    {"text": "The Chartreux is a rare French breed known for its blue-gray coat and copper eyes — Carthusian monks may have bred them in the Middle Ages."},
    {"text": "Somali cats are essentially long-haired Abyssinians — they have bushy tails and ticked coats, earning them the nickname 'fox cats.'"},
    {"text": "The Himalayan is a cross between Persian and Siamese, with the Persian's body and coat but the Siamese's color points."},
    {"text": "The Egyptian Mau is the fastest domestic cat breed, reaching speeds of 30 mph — it's also the only naturally spotted domestic breed.", "type": "did-you-know"},
    {"text": "The Ragamuffin was developed from the Ragdoll breed and is known for being extremely docile and affectionate with a teddy-bear appearance."},
    {"text": "The Balinese is essentially a long-haired Siamese — despite the name, it has no connection to Bali."},
    {"text": "The Ocicat looks like a small wild ocelot but is entirely domestic, created by crossing Abyssinians, Siamese, and American Shorthairs."},
    {"text": "The Japanese Bobtail is considered lucky in Japan — the famous 'maneki-neko' (beckoning cat) figurine is based on this breed."},
    {"text": "The Singapura is the smallest domestic cat breed, weighing only 4-8 pounds — it originated from street cats in Singapore.", "type": "did-you-know"},
    {"text": "The LaPerm has a unique curly coat that results from a spontaneous mutation discovered in Oregon in 1982."},
    {"text": "The Turkish Van is known as the 'swimming cat' because it actually enjoys water — it originated near Lake Van in eastern Turkey."},
    {"text": "The Korat is one of the oldest cat breeds from Thailand, considered a symbol of good luck — they have a distinctive silver-blue coat."},
    {"text": "The Bombay cat was bred to look like a miniature black panther — it was created by crossing Burmese with black American Shorthairs."},
    {"text": "The Havana Brown is one of the rarest breeds, with fewer than 1,000 in the world — it has a distinctive chocolate-brown coat.", "type": "did-you-know"},
    {"text": "The Toyger was bred to look like a miniature tiger, with striped markings on a glittery orange coat."},
    {"text": "The American Curl has distinctively backward-curling ears caused by a spontaneous mutation first seen in a stray cat in California in 1981."},
    {"text": "The Pixiebob is a large domestic cat bred to resemble the North American Bobcat — some have polydactyl (extra) toes."},

    # === CAT SCIENCE & BIOLOGY ===
    {"text": "Cats sleep an average of 12-16 hours per day — kittens and senior cats may sleep up to 20 hours."},
    {"text": "A cat's purr vibrates at a frequency of 25-150 Hz, which can promote healing of bones, tendons, and muscles.", "type": "did-you-know"},
    {"text": "Cats can rotate their ears 180 degrees independently, with 32 muscles controlling each ear."},
    {"text": "A cat can jump up to six times its body length in a single bound."},
    {"text": "Cats have over 200 million scent receptors in their noses — far more than humans' 5 million."},
    {"text": "Cats can't taste sweetness — they lack the taste receptor gene for sweet flavors."},
    {"text": "A cat's whiskers are roughly as wide as its body, helping it gauge whether it can fit through tight spaces.", "type": "did-you-know"},
    {"text": "Cats have a reflective layer behind their retinas called the tapetum lucidum, giving them vision about six times better than humans in low light."},
    {"text": "A cat has 230 bones — more than a human's 206. The extra bones are mostly in their spine and tail, giving them remarkable flexibility."},
    {"text": "Cats spend about 30-50% of their waking hours grooming themselves."},
    {"text": "A domestic cat can run at speeds up to 30 mph in short bursts."},
    {"text": "Cats have a 'righting reflex' that allows them to twist their body mid-air to land on their feet when falling.", "type": "did-you-know"},
    {"text": "Cat claws are retractable — they extend only when needed for hunting, climbing, or self-defense. Cheetahs are the only cats that can't fully retract their claws."},
    {"text": "Cats have a special collarbone that isn't attached to other bones, allowing them to squeeze through any space their head can fit through."},
    {"text": "A cat's field of vision is about 200 degrees, compared to humans' 180 degrees."},
    {"text": "Cats have a third eyelid called a nictitating membrane that protects their eyes from dust and damage."},
    {"text": "A group of cats is called a 'clowder,' and a group of kittens is called a 'kindle.'", "type": "did-you-know"},
    {"text": "Cats have scent glands on their cheeks, paws, and the base of their tail — when they rub against you, they're marking you as theirs."},
    {"text": "A cat's heart beats approximately 110-140 times per minute — nearly twice the rate of a human heart."},
    {"text": "Cats can hear ultrasonic sounds that mice and rats use to communicate, which is one reason they're such effective hunters."},
    {"text": "Female cats are typically right-pawed, while male cats tend to be left-pawed.", "type": "did-you-know"},
    {"text": "Cats have a specialized organ called the vomeronasal (Jacobson's) organ in the roof of their mouth — the 'Flehmen response' (open-mouth face) activates it."},
    {"text": "A cat's average body temperature is 101.5°F (38.6°C), slightly higher than a human's."},
    {"text": "Kittens are born with blue eyes — their permanent eye color doesn't develop until about 6-7 weeks of age."},
    {"text": "Cats can make over 100 different vocalizations — dogs can make only about 10.", "type": "did-you-know"},
    {"text": "Cats have 473 taste buds compared to humans' 9,000 — they rely more on smell than taste when eating."},
    {"text": "A cat's spine has 53 vertebrae (humans have 34), giving them extraordinary flexibility and the ability to twist and contort."},
    {"text": "Cats cannot see directly below their noses, which is why they sometimes can't find treats placed right in front of them."},

    # === CAT HISTORY ===
    {"text": "Cats were first domesticated about 10,000 years ago in the Near East, likely in the Fertile Crescent region."},
    {"text": "Ancient Egyptians worshipped cats and associated them with the goddess Bastet — killing a cat, even accidentally, was punishable by death.", "type": "did-you-know"},
    {"text": "When ancient Egyptian cats died, their owners shaved their eyebrows in mourning and the cats were often mummified."},
    {"text": "During the Middle Ages in Europe, cats were associated with witchcraft and were persecuted alongside accused witches."},
    {"text": "The Black Death may have been worsened by the killing of cats during the Middle Ages, allowing rat populations to explode."},
    {"text": "Cats arrived in the Americas on ships with European colonists, valued for their rat-catching abilities."},
    {"text": "In Norse mythology, the goddess Freya's chariot was pulled by two large cats named Bygul and Trjegul."},
    {"text": "The first formal cat show was held at the Crystal Palace in London in 1871, organized by Harrison Weir.", "month": 7, "day": 13},
    {"text": "The Cat Fanciers' Association (CFA) was founded in 1906 and is the world's largest registry of pedigreed cats."},
    {"text": "In Japan, cats have been considered good luck for centuries — the 'maneki-neko' beckoning cat originated in the 17th century.", "type": "did-you-know"},
    {"text": "Cats were associated with the prophet Muhammad in Islamic tradition — he reportedly loved cats and let them sleep on his prayer mat."},
    {"text": "During World War I and II, cats served as ship cats to control vermin — many received military honors."},
    {"text": "The phrase 'cat got your tongue' dates back to the English Navy, where the 'cat-o'-nine-tails' whip would render sailors speechless."},
    {"text": "The Cat Fanciers' Association currently recognizes 45 pedigreed cat breeds."},

    # === FAMOUS CATS ===
    {"text": "Grumpy Cat (real name Tardar Sauce) became an internet sensation in 2012 and was worth an estimated $100 million before her death in 2019.", "type": "did-you-know"},
    {"text": "Félicette was the first cat in space, launched by France on October 18, 1963. She survived the flight and returned safely.", "month": 10, "day": 18},
    {"text": "A cat named Unsinkable Sam survived three separate ship sinkings during World War II — the Bismarck, HMS Cossack, and HMS Ark Royal.", "type": "did-you-know"},
    {"text": "Tom and Jerry, the classic cartoon, debuted in 1940 and has won seven Academy Awards — more than any other animated series."},
    {"text": "The Cheshire Cat from 'Alice's Adventures in Wonderland' (1865) is known for its distinctive grin that remains after the rest of the cat disappears."},
    {"text": "Garfield, the lasagna-loving orange tabby, was created by Jim Davis in 1978 and appears in approximately 2,580 newspapers worldwide."},
    {"text": "Hello Kitty, created by Sanrio in 1974, is technically not a cat — Sanrio has stated she's a cartoon character who happens to look like a cat.", "type": "did-you-know"},
    {"text": "Dewey Readmore Books was a famous library cat who lived in the Spencer Public Library in Iowa from 1988 to 2006 and became a bestselling book subject."},
    {"text": "Larry the Cat has been the Chief Mouser at 10 Downing Street since 2011 — he's outlasted multiple Prime Ministers."},
    {"text": "Stubbs, an orange tabby, served as the honorary mayor of Talkeetna, Alaska, for 20 years from 1997 to 2017.", "type": "did-you-know"},
    {"text": "Lil Bub, a famous internet cat born with several genetic mutations including dwarfism, helped raise over $700,000 for animal charities."},
    {"text": "The Catbus from Studio Ghibli's 'My Neighbor Totoro' (1988) is one of the most beloved fictional cat characters in animation."},
    {"text": "Cat Stevens (now Yusuf Islam) took his stage name because his girlfriend said he had 'cat-like' eyes."},
    {"text": "A cat named Creme Puff from Austin, Texas, holds the record for the oldest cat ever — she lived to be 38 years and 3 days old.", "type": "did-you-know"},
    {"text": "Salem from 'Sabrina the Teenage Witch' was a warlock turned into a cat — the animatronic puppet cost around $25,000."},
    {"text": "Mrs. Chippy was the ship cat on Ernest Shackleton's ill-fated Antarctic expedition aboard the Endurance in 1914."},
    {"text": "Keyboard Cat, a viral video of a cat playing a keyboard, has been viewed over 50 million times since being uploaded in 2007."},

    # === CAT BEHAVIOR ===
    {"text": "Cats knead (make 'biscuits') as a comforting behavior carried over from kittenhood — kittens knead their mother to stimulate milk flow."},
    {"text": "Slow blinking at a cat is like giving them a kiss — studies show cats return slow blinks and are more likely to approach a slow-blinking human.", "type": "did-you-know"},
    {"text": "Cats bring dead prey to their owners not as gifts, but because they view you as a poor hunter who needs feeding — essentially they're trying to teach you."},
    {"text": "When a cat shows you its belly, it's a sign of trust — but it doesn't necessarily mean they want a belly rub."},
    {"text": "Cats headbutt (bunting) to mark you with scent glands on their forehead, claiming you as part of their social group."},
    {"text": "The 'chattering' sound cats make when watching birds through windows is thought to be a reflexive hunting behavior or frustration."},
    {"text": "Cats can hold grudges — they have episodic memory and can remember specific negative experiences for years."},
    {"text": "A cat's tail position communicates mood — straight up means happy, puffed up means frightened, tucked means insecure.", "type": "did-you-know"},
    {"text": "Cats are crepuscular, meaning they're most active during dawn and dusk — not nocturnal as commonly believed."},
    {"text": "Catnip affects about 50-70% of cats — the reaction is genetic and inherited. Big cats like lions and tigers also respond to catnip."},
    {"text": "Cats have a strong prey drive triggered by movement — this is why laser pointers and feather toys are so effective."},
    {"text": "When cats arch their backs and puff up their fur, they're trying to appear larger and more intimidating to potential threats."},
    {"text": "Cats scratch furniture not to sharpen their claws, but to stretch their muscles, mark territory with scent glands in their paws, and shed old claw sheaths.", "type": "did-you-know"},
    {"text": "A cat's purr may serve as a self-healing mechanism — the vibration frequencies can improve bone density and promote wound healing."},
    {"text": "Cats have a highly developed sense of time and can anticipate regular events like feeding times with remarkable accuracy."},
    {"text": "The 'zoomies' (mad dashes around the house) are a way for indoor cats to release pent-up energy from their natural hunting instincts."},

    # === CAT HEALTH ===
    {"text": "Cats are obligate carnivores — they must eat meat to survive and cannot thrive on a vegetarian diet."},
    {"text": "Lilies are extremely toxic to cats — even small amounts of pollen can cause fatal kidney failure.", "type": "did-you-know"},
    {"text": "Cats can develop kidney disease, hyperthyroidism, and diabetes — the three most common health issues in older cats."},
    {"text": "Indoor cats live an average of 12-18 years, while outdoor cats live only 2-5 years on average due to hazards."},
    {"text": "Cats need taurine, an essential amino acid found only in animal protein — without it, they can go blind and develop heart problems."},
    {"text": "Hairballs (trichobezoars) occur because cats swallow loose fur during grooming — their backward-facing tongue barbs make it impossible to spit out."},
    {"text": "Dental disease affects about 70% of cats by age three, making dental care an important aspect of cat health."},
    {"text": "Cats should never be given aspirin, acetaminophen (Tylenol), or ibuprofen — even small doses can be fatal.", "type": "did-you-know"},
    {"text": "FIV (Feline Immunodeficiency Virus) is similar to HIV in humans — it weakens the immune system but cats can live for years with proper care."},
    {"text": "Cats can be allergic to humans — specifically to human dander, much like humans can be allergic to cat dander."},

    # === CAT CULTURE & POP CULTURE ===
    {"text": "The internet's obsession with cats has made cat videos the most-watched content category on YouTube, with over 26 billion views."},
    {"text": "In ancient Egypt, the penalty for smuggling a cat out of the country was death."},
    {"text": "Black cats are considered good luck in Japan, Scotland, and much of England — it's mainly in the US that they're associated with bad luck.", "type": "did-you-know"},
    {"text": "The musical 'Cats' by Andrew Lloyd Webber is based on T.S. Eliot's 'Old Possum's Book of Practical Cats' and has been seen by over 73 million people worldwide."},
    {"text": "Cat cafés originated in Taipei, Taiwan in 1998 and became hugely popular in Japan before spreading worldwide."},
    {"text": "Ernest Hemingway loved polydactyl (extra-toed) cats — about 60 of their descendants still live at his former home in Key West, Florida.", "type": "did-you-know"},
    {"text": "The Hermitage Museum in St. Petersburg, Russia, employs about 70 cats to protect its art collection from mice."},
    {"text": "National Cat Day is celebrated on October 29th in the United States.", "month": 10, "day": 29},
    {"text": "In Islam, cats are considered clean animals and are allowed to enter mosques and homes freely."},
    {"text": "Abraham Lincoln was the first US president to keep cats in the White House — he had four: Tabby, Dixie, Catamount (an actual bobcat), and Fido."},
    {"text": "The phrase 'curiosity killed the cat' originally was 'care killed the cat' in Ben Jonson's 1598 play, where 'care' meant worry."},
    {"text": "In Japan, the maneki-neko (beckoning cat) with a raised left paw attracts customers, while a raised right paw attracts wealth.", "type": "did-you-know"},
    {"text": "The 'Crazy Cat Lady' stereotype has been studied by researchers who found that cat owners are no more likely to have mental health issues than anyone else."},
    {"text": "CatCon, a cat convention for cat lovers, has been held annually in the US since 2015 and attracts thousands of attendees."},

    # === CAT RECORDS ===
    {"text": "The largest domestic cat breed is the Savannah, which can stand up to 17 inches at the shoulder and weigh over 25 pounds."},
    {"text": "A cat named Dusty had 420 kittens over her lifetime — the most ever recorded.", "type": "did-you-know"},
    {"text": "The richest cat in history was Blackie, whose owner left him £7 million (about $12.5 million) in his will."},
    {"text": "The loudest purr by a domestic cat was 67.8 decibels, achieved by a cat named Merlin in the UK — equivalent to a running dishwasher."},
    {"text": "A cat named Didga holds the Guinness World Record for most tricks performed by a cat in one minute — 24 tricks."},
    {"text": "The longest cat ever measured was a Maine Coon named Stewie at 48.5 inches (123 cm) from nose to tail tip.", "type": "did-you-know"},
    {"text": "A cat named Andy survived a fall from the 16th floor of an apartment building in Florida, landing on a concrete sidewalk and walking away."},
    {"text": "The most expensive cat breed is the Ashera, a hybrid breed that can cost up to $125,000."},
    {"text": "A cat named Creme Puff lived to 38 years old — roughly equivalent to 168 human years."},
    {"text": "The smallest cat breed is the Singapura, with adult females weighing as little as 4 pounds."},

    # === CATS AND HUMANS ===
    {"text": "Cat owners have a 30% lower risk of dying from heart attacks and strokes compared to non-cat owners, according to a University of Minnesota study.", "type": "did-you-know"},
    {"text": "Toxoplasmosis, caused by the parasite Toxoplasma gondii found in cat feces, infects about 30-50% of the world's human population but is usually asymptomatic."},
    {"text": "Cats domesticated themselves — they were attracted to human grain stores that attracted rodents, and humans tolerated them for pest control."},
    {"text": "Research shows that cats recognize their owners' voices but often choose to ignore them — scientists call this 'domestication on their own terms.'", "type": "did-you-know"},
    {"text": "About 95.6 million cats are owned as pets in the United States, making cats the second most popular pet after freshwater fish."},
    {"text": "Cat allergies are caused by the protein Fel d 1 in cat saliva, skin, and urine — not by cat fur itself."},
    {"text": "Petting a cat releases oxytocin in both the cat and the human, reducing stress and promoting bonding."},
    {"text": "Cats can recognize their names but studies show they respond much less reliably than dogs — they just don't care as much."},
    {"text": "Multi-cat households should have one litter box per cat plus one extra — the 'n+1' rule recommended by veterinary behaviorists."},
    {"text": "Indoor cats should have enrichment activities — puzzle feeders, climbing trees, and window perches are essential for mental health."},
    {"text": "Cats have been shown to reduce anxiety and depression in their owners — even watching cat videos has measurable stress-reducing effects.", "type": "did-you-know"},

    # === MORE FUN FACTS ===
    {"text": "A cat can spend up to one-third of its waking life grooming — about 10,950 hours over a 15-year lifespan."},
    {"text": "Cats have a dominant paw — about 40% are left-pawed, 20% are right-pawed, and 40% are ambidextrous."},
    {"text": "Isaac Newton is credited with inventing the cat flap (cat door) so his cat could come and go without disturbing his experiments.", "type": "did-you-know"},
    {"text": "A cat's tongue has tiny backward-facing hooks called papillae that help them groom and strip meat from bones."},
    {"text": "Cats can drink seawater because their kidneys are efficient enough to filter out the salt."},
    {"text": "The average domestic cat can kill up to 1,000 prey animals per year — they're one of the most effective predators on Earth.", "type": "did-you-know"},
    {"text": "Cats have been blamed for the extinction of at least 63 species worldwide, making them one of the most harmful invasive species."},
    {"text": "A cat can survive falls from great heights by spreading its body like a parachute — this is called the 'high-rise syndrome.'"},
    {"text": "Cats have a 'primordial pouch' — the loose skin on their belly that protects internal organs during fights and allows them to stretch while running."},
    {"text": "Male cats are called toms, female cats are called queens, and baby cats are called kittens."},
    {"text": "Cats' whiskers shed and regrow naturally — they should never be trimmed as they are essential sensory tools."},
    {"text": "A cat named Towser, a tortoiseshell at the Glenturret Distillery in Scotland, caught an estimated 28,899 mice in her 24-year career.", "type": "did-you-know"},
    {"text": "Orange cats are almost always male — about 80% of orange tabbies are male due to the genetics of coat color."},
    {"text": "Calico cats are almost always female — the calico pattern requires two X chromosomes, so male calicos are extremely rare (1 in 3,000)."},
    {"text": "Tuxedo cats (black and white) got their name from their formal appearance — Felix the Cat and Sylvester are famous tuxedo cats.", "type": "did-you-know"},
    {"text": "All tabby cats have an 'M' marking on their forehead — according to legend, the Prophet Muhammad gave them this mark after one kept him warm."},
    {"text": "Cats can be right-eyed or left-eyed — they tend to lead with one eye when focusing on objects."},
    {"text": "Kittens from the same litter can have different fathers — this is called 'superfecundation.'", "type": "did-you-know"},
    {"text": "The Jacobson's organ allows cats to 'taste' the air — the funny face they make (Flehmen response) is them drawing air across this organ."},
    {"text": "Cats have been kept aboard ships as mousers for thousands of years — most naval vessels historically had at least one ship's cat."},
    {"text": "The 'Halloween cat' pose — arched back, puffed fur, sideways stance — is designed to make the cat look as large as possible to threats."},
    {"text": "Cats bury their waste as an instinctive behavior to hide their scent from predators — dominant cats sometimes leave waste uncovered to mark territory."},
    {"text": "The gene for polydactylism (extra toes) is dominant — if one parent is polydactyl, about 50% of kittens will be too.", "type": "did-you-know"},
    {"text": "Cat urine glows under black light because of phosphorus — this is how investigators find hidden cat marking in homes."},
    {"text": "The original LOLcats meme started on 4chan in 2006 with 'Caturday' — a weekly tradition of posting funny cat photos with misspelled captions."},
    {"text": "A cat's clavicle (collarbone) is free-floating, attached only by muscles — this gives them remarkable flexibility to squeeze through tight spaces."},
    {"text": "Tortoiseshell cats are called 'torties' and the pattern occurs almost exclusively in females due to X-linked genetics.", "type": "did-you-know"},
    {"text": "A cat named Oscar at the Steere House Nursing Center in Rhode Island accurately predicted the deaths of over 50 patients by curling up next to them."},
    {"text": "Cats can swivel their ears independently like satellite dishes to pinpoint the exact location of sounds."},
    {"text": "The 'catnip response' is inherited and about 50% of cats don't react to catnip at all — kittens under 6 months are also immune."},
    {"text": "A cat's normal resting respiratory rate is 20-30 breaths per minute — significantly less than a human's during exercise."},
    {"text": "Black cats were revered by sailors and fishermen who believed they would bring good luck and ensure a safe return.", "type": "did-you-know"},
    {"text": "Cats are lactose intolerant as adults — despite the popular image, milk can cause stomach problems for most grown cats."},
    {"text": "The 'elevator butt' response, when cats raise their rear end when scratched at the base of their tail, is a nerve reflex."},
    {"text": "A cat's brain is about 90% similar to a human brain — cats and humans have nearly identical regions responsible for emotion."},
    {"text": "An unspayed female cat can produce up to 100 kittens during her lifetime, and a single pair of cats could theoretically produce 420,000 descendants in 7 years.", "type": "did-you-know"},
    {"text": "Cats can be allergic to fleas — a single flea bite can cause severe itching that lasts for weeks (flea allergy dermatitis)."},
    {"text": "Cats evolved to eat 8-12 small meals throughout the day — this is why many vets recommend puzzle feeders rather than two large meals."},
    {"text": "The average cat's gestation period is about 63-65 days — roughly 9 weeks."},
    {"text": "Cats can develop separation anxiety — symptoms include excessive vocalization, elimination outside the litter box, and destructive behavior."},
    {"text": "The 'cat eye' eyeliner look in makeup was inspired by feline eyes and became a popular beauty trend in the 1950s."},
    {"text": "Cats have been found to have at least 230 unique facial expressions, according to a 2023 study from the University of Kansas."},
    {"text": "International Cat Day is celebrated on August 8th, established by the International Fund for Animal Welfare in 2002.", "month": 8, "day": 8},
    {"text": "Cats have four rows of whiskers on each side of their face, and the pattern is as unique as a human fingerprint.", "type": "did-you-know"},
    {"text": "Cat shows have evolved from simple judging of breeds to elaborate events with agility courses, costume contests, and 'Supreme' champion categories."},
    {"text": "Cats are on every continent except Antarctica — feral cat populations exist on every inhabited continent."},
    {"text": "The 'crazy eyes' (dilated pupils during play) in cats indicate heightened arousal — their pupils can dilate to nearly full-eye size during hunting behavior."},
    {"text": "Ancient Egyptian families would go into mourning when their cat died, and the city of Bubastis held grand festivals in honor of the cat goddess Bastet."},
    {"text": "Cats can detect earthquake tremors up to 10-15 minutes before humans due to their sensitive paw pads.", "type": "did-you-know"},
    {"text": "The fastest domestic cat breed, the Egyptian Mau, can sprint at 30 mph — that's nearly as fast as a Greyhound."},
    {"text": "A cat's normal heart rate is about 140-220 beats per minute, with kittens having even faster rates."},
    {"text": "Cats produce the 'chirp' or 'trill' sound (a combination of a meow and a purr) as a friendly greeting used between mothers and kittens."},
    {"text": "The oldest evidence of human-cat cohabitation is a 9,500-year-old grave in Cyprus where a cat was buried alongside its human.", "type": "did-you-know"},
    {"text": "Adult cats primarily meow to communicate with humans, not with other cats — cat-to-cat communication mainly uses body language and scent."},
    {"text": "The 'snow leopard tail bite' pose, where a cat holds its own tail in its mouth, has gone viral on social media as an adorable feline quirk."},
    {"text": "White cats with blue eyes are significantly more likely to be deaf — about 65-85% are born with hearing impairment."},
    {"text": "Cats have been trained to act in movies and TV shows using 'clicker training' — the same positive reinforcement method used with dogs."},
    {"text": "A cat's claws grow continuously and need regular trimming or scratching surfaces to prevent overgrowth."},
    {"text": "Cats can jump about 5-6 times their body height from a standing position.", "type": "did-you-know"},
    {"text": "The 'cat loaf' position (paws tucked under the body) is a sign of relaxation but also readiness — they can spring up quickly if needed."},
    {"text": "Toxoplasma gondii, the parasite found in cat feces, has been studied for its potential effects on human behavior and risk-taking."},
    {"text": "A cat's 'social roll' (flopping onto their back) is a greeting behavior that shows trust but is not always an invitation to touch their belly."},
    {"text": "Cats maintain territories of varying sizes — indoor cats may claim a single room, while feral cats can patrol territories of several square miles."},
    {"text": "The viral 'If I Fits, I Sits' phenomenon reflects cats' natural instinct to seek confined spaces for warmth and security.", "type": "did-you-know"},
    {"text": "Cat paws can act as shock absorbers, cushioning their landings — this is why cats can jump from heights that would injure most animals."},
    {"text": "Cats have specialized barbed tongues that can strip meat from bone and act as a comb during grooming."},
    {"text": "The oldest known pet cat was found in a 9,500-year-old Neolithic village on the Mediterranean island of Cyprus."},
    {"text": "A cat named Nora became famous for playing the piano — her videos have been viewed millions of times and even inspired a concerto.", "type": "did-you-know"},
    {"text": "Cats have an incredible ability to find their way home over long distances — a phenomenon called 'psi-trailing' that scientists still don't fully understand."},
    {"text": "The world's first cloned cat, named CC (Copy Cat), was born at Texas A&M University in December 2001.", "month": 12, "day": 22},
    {"text": "Cats can learn to use human toilets — complete toilet training kits are available commercially."},
]

data = {"hobby": "Cats", "facts": facts}

path = 'extension/data/facts/cats.json'
import os
os.makedirs(os.path.dirname(path), exist_ok=True)
with open(path, 'w') as f:
    json.dump(data, f, ensure_ascii=False)

print(f"Created cats.json with {len(facts)} facts")
