#!/usr/bin/env python3
"""Create dogs.json with 400+ facts about dogs."""
import json, os

facts = [
    # === BREED PROFILES ===
    {"text": "The Labrador Retriever has been the most popular dog breed in America for over 30 consecutive years according to the AKC."},
    {"text": "German Shepherds were originally bred in 1899 by Max von Stephanitz to be the perfect herding dog — they're now the world's top police and military breed.", "type": "did-you-know"},
    {"text": "Golden Retrievers were developed in Scotland in the mid-1800s by Lord Tweedmouth, who crossed a Yellow Retriever with the now-extinct Tweed Water Spaniel."},
    {"text": "French Bulldogs surpassed Labrador Retrievers as the #1 AKC breed in 2022 for the first time in 31 years."},
    {"text": "The Bulldog was originally bred for bull-baiting in 13th-century England — when the sport was banned in 1835, breeders transformed them into gentle companions.", "type": "did-you-know"},
    {"text": "Poodles come in three sizes (Standard, Miniature, Toy) and were originally bred as water retrievers in Germany — their fancy haircut was functional, not fashionable."},
    {"text": "Beagles have approximately 220 million scent receptors compared to about 5 million in humans, making them one of the best scent-tracking breeds."},
    {"text": "Rottweilers were originally used by Roman legions to herd cattle and guard camps — the breed gets its name from the German town of Rottweil."},
    {"text": "The Dachshund was bred in Germany to hunt badgers — 'Dachs' means badger and 'Hund' means dog in German.", "type": "did-you-know"},
    {"text": "Yorkshire Terriers were originally bred to catch rats in clothing mills in northern England during the Industrial Revolution."},
    {"text": "The Siberian Husky was bred by the Chukchi people of northeastern Asia to pull sleds over vast frozen expanses."},
    {"text": "Boxers got their name from their tendency to stand on hind legs and 'box' with their front paws during play."},
    {"text": "The Great Dane is one of the tallest dog breeds — a Great Dane named Zeus held the record at 44 inches at the shoulder."},
    {"text": "Doberman Pinschers were created in the 1890s by German tax collector Karl Friedrich Louis Dobermann, who wanted a dog for protection on his rounds.", "type": "did-you-know"},
    {"text": "Australian Shepherds are not actually from Australia — they were developed in the western United States to herd livestock."},
    {"text": "Cavalier King Charles Spaniels are named after King Charles II of England, who was so devoted to the breed he reportedly neglected state affairs."},
    {"text": "The Pembroke Welsh Corgi was the favorite breed of Queen Elizabeth II, who owned more than 30 Corgis during her reign."},
    {"text": "Border Collies are widely regarded as the most intelligent dog breed, capable of learning hundreds of words and commands."},
    {"text": "The Shih Tzu was bred as a lap dog for Chinese royalty and means 'lion dog' in Mandarin."},
    {"text": "Cocker Spaniels get their name from their excellence at hunting woodcock, a type of game bird."},
    {"text": "The Bernese Mountain Dog originated in the Swiss Alps and was used to pull carts, herd cattle, and guard farms."},
    {"text": "Chihuahuas are the smallest recognized dog breed and are named after the Mexican state of Chihuahua where they were discovered.", "type": "did-you-know"},
    {"text": "The Akita is a national treasure of Japan — when a child is born, families are often gifted an Akita figurine symbolizing health and happiness."},
    {"text": "Dalmatians are born completely white — their spots develop as they grow during the first few weeks of life.", "type": "did-you-know"},
    {"text": "The Weimaraner was originally bred for hunting large game like boar, bear, and deer for German nobility."},
    {"text": "Pit Bull is not a single breed but a term covering several breeds including the American Pit Bull Terrier, American Staffordshire Terrier, and Staffordshire Bull Terrier."},
    {"text": "The Maltese is one of the oldest toy breeds, with a history stretching back at least 2,000 years to ancient Mediterranean civilizations."},
    {"text": "Bloodhounds can follow a scent trail that is over 300 hours (12+ days) old and their tracking results are admissible in court.", "type": "did-you-know"},
    {"text": "The Newfoundland is an excellent swimmer with webbed feet and a water-resistant coat — they were originally used by fishermen in Canada."},
    {"text": "The Pomeranian was once a large sled-pulling dog — Queen Victoria bred them down to toy size in the late 1800s."},
    {"text": "The Whippet can reach speeds of up to 35 mph, making them the fastest domesticated animal of their size."},
    {"text": "Jack Russell Terriers were bred by Reverend John Russell in 1800s England specifically for fox hunting."},
    {"text": "The Saint Bernard was originally bred by monks at the Great St. Bernard Hospice in the Swiss Alps for rescue work in the snowy mountains."},
    {"text": "Greyhounds can reach speeds of up to 45 mph, making them the fastest dog breed in the world.", "type": "did-you-know"},
    {"text": "The Irish Wolfhound is the tallest of all dog breeds and was originally bred to hunt wolves in Ireland."},
    {"text": "The Chow Chow has a distinctive blue-black tongue — they're one of only two breeds with this trait (the other is the Shar-Pei)."},
    {"text": "The Shar-Pei's loose, wrinkly skin was originally bred to make it difficult for opponents to grab during dog fighting in ancient China."},
    {"text": "Basset Hounds have the second-best sense of smell of any breed after the Bloodhound and are built low to the ground to stay close to scent trails."},
    {"text": "The Portuguese Water Dog was bred to assist fishermen — they'd herd fish into nets, retrieve tackle, and even carry messages between boats."},
    {"text": "The Bichon Frise was a favorite of French royalty and was often seen in paintings by Francisco de Goya."},
    {"text": "English Bulldogs have such large heads that approximately 80% must be delivered by cesarean section.", "type": "did-you-know"},

    # === FAMOUS DOGS ===
    {"text": "Hachiko, an Akita in Japan, waited at Shibuya Station every day for nearly 10 years after his owner's death — a bronze statue now stands in his honor.", "type": "did-you-know"},
    {"text": "Balto, a Siberian Husky, led a sled team through a blizzard to deliver diphtheria antitoxin to Nome, Alaska, in 1925, saving countless lives.", "month": 2, "day": 2},
    {"text": "Laika, a Moscow stray dog, became the first animal to orbit Earth aboard the Soviet spacecraft Sputnik 2 in 1957.", "month": 11, "day": 3},
    {"text": "Rin Tin Tin was a German Shepherd rescued from a World War I battlefield who became one of Hollywood's biggest stars in the 1920s."},
    {"text": "Lassie, the fictional Rough Collie, first appeared in a 1938 short story and went on to star in movies, TV shows, and books for decades."},
    {"text": "Toto from 'The Wizard of Oz' (1939) was played by a Cairn Terrier named Terry, who earned $125 per week — more than many human actors."},
    {"text": "Buddy, a Golden Retriever, starred in the 'Air Bud' movies and was actually a stray found at the Sierra Nevada by his trainer."},
    {"text": "Bo and Sunny, Portuguese Water Dogs, were the Obama family's White House dogs from 2009 to 2017."},
    {"text": "Fala, President Franklin D. Roosevelt's Scottish Terrier, was so famous that FDR once gave a political speech defending the dog."},
    {"text": "Rex, a King Charles Spaniel, was President Ronald Reagan's dog at the White House."},
    {"text": "Stubby, a Boston Terrier mix, served in World War I and became the most decorated war dog in American history."},
    {"text": "Endal, a Yellow Labrador service dog in the UK, could operate ATMs, elevators, and shopping carts and was named 'Dog of the Millennium.'", "type": "did-you-know"},
    {"text": "Marley, the Yellow Lab from 'Marley & Me,' was based on a real dog whose story became a bestselling book and hit movie."},
    {"text": "Old Yeller, the 1957 Disney movie about a loyal stray dog in 1860s Texas, is considered one of the most emotionally impactful dog films ever made."},
    {"text": "Beethoven, the Saint Bernard from the 1992 film, popularized the breed and led to a surge in Saint Bernard adoptions."},
    {"text": "Smoky, a Yorkshire Terrier found in a foxhole in New Guinea during WWII, is considered the first therapy dog."},

    # === DOG SCIENCE & BIOLOGY ===
    {"text": "Dogs have about 300 million olfactory receptors in their noses, compared to about 6 million in humans."},
    {"text": "A dog's nose print is unique, like a human fingerprint, and can be used to identify individual dogs.", "type": "did-you-know"},
    {"text": "Dogs can hear frequencies up to about 65,000 Hz, while humans can only hear up to about 20,000 Hz."},
    {"text": "Dogs' wet noses help them absorb scent chemicals — the mucus on a dog's nose helps capture tiny scent particles."},
    {"text": "Dogs have three eyelids: an upper lid, a lower lid, and a third lid called a nictitating membrane that keeps their eyes moist."},
    {"text": "Dogs can see in the dark much better than humans due to a special light-reflecting layer behind their retinas called the tapetum lucidum."},
    {"text": "Dogs only sweat through their paw pads — they regulate body temperature primarily through panting."},
    {"text": "A dog's sense of smell is 10,000 to 100,000 times more acute than a human's."},
    {"text": "Dogs can be trained to detect cancer, low blood sugar, seizures, and even COVID-19 through their incredible sense of smell.", "type": "did-you-know"},
    {"text": "Puppies are born deaf, blind, and toothless — they can't see or hear until they're about two weeks old."},
    {"text": "Dogs curl up in a ball when sleeping to protect their vital organs — an instinct inherited from their wild ancestors."},
    {"text": "The average dog can understand about 165 words, while the most intelligent breeds can learn over 250 words."},
    {"text": "Dogs have about 1,700 taste buds compared to humans' 9,000, which is why they're less picky about food."},
    {"text": "A dog's normal body temperature is between 101°F and 102.5°F, slightly higher than a human's 98.6°F."},
    {"text": "Dogs dream during the REM phase of sleep — small dogs dream more frequently than large dogs.", "type": "did-you-know"},
    {"text": "Tail wagging doesn't always mean happiness — a wag to the right indicates positive emotions, while a left wag suggests anxiety or uncertainty."},
    {"text": "Dogs have a specialized organ called Jacobson's organ (vomeronasal organ) that allows them to taste and smell simultaneously."},
    {"text": "A one-year-old dog is roughly equivalent to a 30-year-old human in terms of physical maturity, not 7 as commonly believed."},
    {"text": "Dogs' noses are so sensitive they can detect a teaspoon of sugar in a million gallons of water — the equivalent of two Olympic swimming pools.", "type": "did-you-know"},
    {"text": "Dogs can read human emotions and distinguish between happy and angry human faces, according to research published in Current Biology."},

    # === DOG HISTORY ===
    {"text": "Dogs were the first domesticated animal, with evidence of domestication dating back at least 15,000 years — possibly as far back as 40,000 years."},
    {"text": "All domestic dogs are descendants of wolves — DNA evidence shows they likely descend from an extinct population of Pleistocene wolves.", "type": "did-you-know"},
    {"text": "Ancient Egyptians revered dogs and would shave their eyebrows and mourn when their dog died."},
    {"text": "In medieval Europe, dogs were put on trial and even 'executed' for crimes — there are court records of dog trials dating back to the 1200s."},
    {"text": "The American Kennel Club (AKC) was founded in 1884 and currently recognizes over 200 dog breeds."},
    {"text": "The first dog show was held in Newcastle, England, in 1859, featuring only Pointers and Setters."},
    {"text": "The Westminster Kennel Club Dog Show has been held annually since 1877, making it the second-longest continuously held sporting event in the US after the Kentucky Derby."},
    {"text": "Dogs were widely used in World War I as messengers, sentries, and for detecting mines — an estimated 20,000 dogs served."},
    {"text": "The Basenji is known as the 'barkless dog' — instead of barking, it makes a unique yodeling sound called a 'baroo.'", "type": "did-you-know"},
    {"text": "Ancient Romans used to put 'Cave Canem' (Beware of Dog) mosaics at the entrances of their homes — some can still be seen in Pompeii."},
    {"text": "The Iditarod Trail Sled Dog Race, run annually in Alaska since 1973, covers about 1,000 miles from Anchorage to Nome."},
    {"text": "The Kennel Club in the UK, founded in 1873, was the world's first kennel club and established the first breed standards."},
    {"text": "Dogs have been in space — the Soviet space program launched several dogs into orbit in the 1950s and 60s as part of their space research."},

    # === DOG BEHAVIOR & TRAINING ===
    {"text": "Dogs yawn as a calming signal — if your dog yawns when you're stressed, they may be trying to calm you down or showing empathy."},
    {"text": "Dogs spin in circles before lying down as an instinctive behavior from their wild ancestors who would flatten grass and check for predators."},
    {"text": "Separation anxiety affects about 14% of dogs — symptoms include destructive behavior, barking, and house soiling when left alone."},
    {"text": "Positive reinforcement training is scientifically proven to be more effective than punishment-based methods, according to the American Veterinary Society of Animal Behavior."},
    {"text": "Dogs can be right-pawed or left-pawed, just like humans are right or left-handed — about 50% of dogs show a paw preference.", "type": "did-you-know"},
    {"text": "The 'zoomies' (Frenetic Random Activity Periods or FRAPs) are a normal behavior where dogs release built-up energy in sudden bursts of running."},
    {"text": "Dogs tilt their heads to adjust their ear position and better locate the source of a sound — breeds with floppy ears tilt more often."},
    {"text": "Puppies go through a critical socialization period between 3 and 14 weeks of age — experiences during this window shape their adult temperament."},
    {"text": "Dogs can understand human pointing gestures, a skill even chimpanzees (our closest relatives) cannot reliably master.", "type": "did-you-know"},
    {"text": "Resource guarding — when dogs protect food, toys, or space — is a natural behavior rooted in survival instincts but can be managed with training."},
    {"text": "Dogs lick people for multiple reasons: affection, salt on skin, attention-seeking, or as a submissive gesture."},
    {"text": "A wagging tail held high usually signals confidence, while a low tail wag typically indicates insecurity or submission."},
    {"text": "Dogs can smell fear — when humans are frightened, they produce specific chemicals that dogs can detect.", "type": "did-you-know"},
    {"text": "Clicker training, developed by marine mammal trainer Karen Pryor, uses a clicking sound to mark desired behaviors and is highly effective with dogs."},

    # === DOG HEALTH ===
    {"text": "The average lifespan of a dog is 10-13 years, but smaller breeds tend to live longer than larger breeds."},
    {"text": "Chocolate is toxic to dogs because it contains theobromine, which dogs metabolize much more slowly than humans."},
    {"text": "Grapes, raisins, onions, garlic, and xylitol (a sweetener) are all toxic to dogs and can be life-threatening."},
    {"text": "Hip dysplasia is one of the most common health issues in large breed dogs — it's a genetic condition where the hip joint doesn't develop properly."},
    {"text": "Dogs can get sunburned, especially breeds with thin coats, white fur, or pink skin — dog-safe sunscreen exists for protection.", "type": "did-you-know"},
    {"text": "Dental disease affects over 80% of dogs by age three, making regular dental care one of the most important aspects of dog health."},
    {"text": "Bloat (gastric dilatation-volvulus or GDV) is a life-threatening emergency common in deep-chested breeds like Great Danes and German Shepherds."},
    {"text": "Dogs' ears should be checked regularly — floppy-eared breeds like Basset Hounds and Cocker Spaniels are especially prone to ear infections."},
    {"text": "The 'dog years' formula of 1 human year = 7 dog years is a myth — dogs age faster early in life, then the rate slows down."},
    {"text": "Spaying or neutering can help prevent certain cancers and behavioral issues and typically extends a dog's lifespan by 1-3 years."},

    # === DOG CULTURE & POP CULTURE ===
    {"text": "The phrase 'raining cats and dogs' may have originated in 17th-century England when heavy storms washed stray animals through the streets."},
    {"text": "Scooby-Doo, created in 1969, is a Great Dane — the show has had over 50 years of continuous production in various formats."},
    {"text": "Snoopy from 'Peanuts,' created by Charles M. Schulz in 1950, is a Beagle and one of the most recognizable fictional dogs in the world."},
    {"text": "Pluto, Mickey Mouse's dog, first appeared in a Disney cartoon in 1930 — unlike Goofy, Pluto walks on all fours and doesn't talk."},
    {"text": "Clifford the Big Red Dog, created by Norman Bridwell in 1963, is estimated to be about 25 feet tall in the story."},
    {"text": "The 101 Dalmatians story, written by Dodie Smith in 1956, was inspired by her own Dalmatian, Pongo."},
    {"text": "The Westminster Dog Show 'Best in Show' winner is one of the most prestigious prizes in the dog world, with the winner becoming a celebrity overnight."},
    {"text": "Dog surfing competitions are real events held in California, where dogs ride waves on surfboards judged for confidence and duration."},
    {"text": "The National Dog Show, broadcast on Thanksgiving Day in the US since 2002, draws over 20 million viewers annually.", "type": "did-you-know"},
    {"text": "Instagram dog celebrities like Jiffpom (a Pomeranian) and Doug the Pug have millions of followers and earn significant income from sponsorships."},
    {"text": "The 'Doge' meme featuring a Shiba Inu named Kabosu became one of the internet's most iconic memes and inspired the cryptocurrency Dogecoin.", "type": "did-you-know"},
    {"text": "Lady and the Tramp (1955) features one of the most iconic scenes in movie history — the spaghetti kiss between two dogs."},

    # === DOG RECORDS & EXTREMES ===
    {"text": "The oldest dog ever recorded was an Australian Kelpie named Maggie, who was reported to have lived to 30 years old."},
    {"text": "The tallest dog ever was Zeus, a Great Dane from Michigan, standing 44 inches (111.8 cm) at the shoulder.", "type": "did-you-know"},
    {"text": "The smallest dog ever was a Chihuahua named Milly from Puerto Rico, measuring just 3.8 inches tall."},
    {"text": "The world record for the most tennis balls held in a dog's mouth is 5, set by a Golden Retriever named Finley."},
    {"text": "A Border Collie named Chaser learned the names of over 1,022 objects, demonstrated by selecting them by name from a pile."},
    {"text": "The longest ears on a dog were on a Bloodhound named Tigger — each ear measured 13.75 inches long.", "type": "did-you-know"},
    {"text": "A Greyhound named Star Title holds the record for the highest dog jump at 75.5 inches (6.29 feet)."},
    {"text": "The most puppies in a single litter was 24, born to a Neapolitan Mastiff named Tia in 2004."},
    {"text": "Norman the Scooter Dog, a French Briard, holds a Guinness record for riding a scooter 100 feet in 20.77 seconds."},
    {"text": "The fastest 100 meters on a skateboard by a dog was 19.65 seconds, achieved by a Bulldog named Otto in Peru."},

    # === DOG BREEDS — MORE PROFILES ===
    {"text": "The Alaskan Malamute is one of the oldest Arctic sled dog breeds, bred by the Mahlemut Inuit people of Alaska."},
    {"text": "The Vizsla is known as the 'Velcro dog' because of their intense attachment to their owners — they rarely leave their human's side."},
    {"text": "The Havanese is the national dog of Cuba and the only breed native to the island."},
    {"text": "The Rhodesian Ridgeback was originally bred in southern Africa to track and hold lions at bay — earning the nickname 'African Lion Dog.'", "type": "did-you-know"},
    {"text": "The Papillon gets its name from the French word for 'butterfly' because of its large, wing-shaped ears."},
    {"text": "The Australian Cattle Dog (Blue Heeler) was developed by crossing Dingoes with imported herding dogs to create a breed tough enough for the Australian outback."},
    {"text": "The Samoyed was bred by the Samoyede people of Siberia to herd reindeer and pull sleds — their thick white coats protected them in temperatures of -60°F."},
    {"text": "The English Springer Spaniel is one of the oldest sporting breeds and was used to 'spring' (flush) game from bushes for hunting."},
    {"text": "The Miniature Schnauzer was developed in Germany by crossing Standard Schnauzers with Poodles and Affenpinschers to create a smaller ratting dog."},
    {"text": "The Belgian Malinois has largely replaced the German Shepherd as the preferred breed for military and police work due to its agility and drive."},
    {"text": "The Cane Corso is an Italian mastiff breed whose name roughly translates to 'bodyguard dog' in Latin.", "type": "did-you-know"},
    {"text": "The Brittany (formerly Brittany Spaniel) originated in the Brittany region of France and is one of the most popular pointing breeds for bird hunting."},
    {"text": "The Shiba Inu is the most popular companion dog breed in Japan — they're also one of the oldest domesticated breeds, dating back 3,000 years."},
    {"text": "The Leonberger was created in the 1800s in Leonberg, Germany, to resemble the lion on the town's crest."},
    {"text": "The Chinese Crested comes in two varieties: Hairless (with hair only on head, paws, and tail) and Powderpuff (fully coated)."},
    {"text": "The Xoloitzcuintli (Mexican Hairless Dog) is one of the world's oldest breeds, dating back over 3,000 years to the Aztecs, who believed they could guide souls to the underworld.", "type": "did-you-know"},

    # === WORKING DOGS ===
    {"text": "Guide dogs for the blind were first trained in Germany during World War I to assist blinded veterans."},
    {"text": "Search and rescue dogs can locate survivors buried under rubble, snow, or water — they can cover terrain much faster than human teams."},
    {"text": "Therapy dogs are used in hospitals, nursing homes, schools, and disaster areas — petting a dog has been shown to lower blood pressure and reduce stress hormones."},
    {"text": "TSA uses Beagles in airports (the 'Beagle Brigade') to sniff out prohibited agricultural products in passengers' luggage.", "type": "did-you-know"},
    {"text": "Avalanche rescue dogs can locate buried victims in minutes — a task that might take a human team hours with probes."},
    {"text": "Cadaver dogs are specially trained to detect human remains and have been used in forensic investigations and disaster recovery worldwide."},
    {"text": "Herding dogs like Border Collies use 'the eye' — an intense stare that controls livestock movement without physical contact."},
    {"text": "Service dogs can be trained to alert diabetic owners to dangerous blood sugar levels by detecting chemical changes in their breath or sweat."},
    {"text": "Military working dogs are so valued that they are given ranks — traditionally one rank higher than their handler to discourage mistreatment.", "type": "did-you-know"},
    {"text": "Cairo, a Belgian Malinois, was part of the Navy SEAL team that conducted the Osama bin Laden raid in 2011."},

    # === DOG CARE & OWNERSHIP ===
    {"text": "There are approximately 90 million pet dogs in the United States, making dogs the most popular pet in the country."},
    {"text": "Americans spend over $136 billion annually on their pets, with a significant portion going to veterinary care, food, and grooming."},
    {"text": "The average cost of owning a dog is $1,500-$2,000 per year for food, veterinary care, grooming, and supplies."},
    {"text": "Dogs should not eat cooked bones — they can splinter and cause internal damage. Raw bones are generally considered safer under supervision."},
    {"text": "A dog's diet should be about 18-25% protein — higher for puppies and active breeds, lower for seniors."},
    {"text": "Regular exercise for dogs isn't just physical — mental stimulation through puzzle toys, training, and scent games is equally important for well-being."},
    {"text": "Dogs need about 12-14 hours of sleep per day, with puppies needing up to 18-20 hours.", "type": "did-you-know"},
    {"text": "Crate training, when done properly, takes advantage of a dog's natural denning instinct and provides a safe, comfortable space."},
    {"text": "Dog parks first appeared in the 1980s in Berkeley, California — today there are thousands across the United States."},
    {"text": "Microchipping a dog costs $25-$50 and dramatically increases the chances of being reunited if the dog is lost."},
    {"text": "Dogs should visit the vet at least once a year for wellness exams and vaccinations — twice a year for senior dogs over 7 years old."},

    # === DOG FUN FACTS ===
    {"text": "Three dogs survived the sinking of the Titanic in 1912 — two Pomeranians and one Pekingese, all from first-class cabins.", "month": 4, "day": 15},
    {"text": "The Saluki is considered one of the oldest dog breeds, with evidence of their existence dating back to 329 BC in ancient Egypt.", "type": "did-you-know"},
    {"text": "A Labrador Retriever named Endal was the first dog to ride on the London Eye."},
    {"text": "Dogs can be blood donors — there are canine blood banks and dog blood types (DEA 1.1, DEA 1.2, etc.)."},
    {"text": "The Norwegian Lundehund has six toes on each foot and extremely flexible joints, originally bred to climb steep cliffs to hunt puffins.", "type": "did-you-know"},
    {"text": "Paul McCartney reportedly recorded an ultrasonic whistle at the end of 'A Day in the Life' by The Beatles, which only dogs can hear."},
    {"text": "The world's most expensive dog breed is the Tibetan Mastiff — one was sold for $1.5 million in China in 2014."},
    {"text": "In 1860, two dogs survived the shipwreck of the Ann Saunders by swimming three miles to shore in a storm."},
    {"text": "Dogs can smell time — they notice the fading scent of their owners throughout the day and can predict when they'll return home."},
    {"text": "A dog named Seamus became politically famous when Mitt Romney admitted to strapping his dog's carrier to the roof of his car during a road trip."},
    {"text": "The phrase 'dog days of summer' comes from the ancient Romans, who associated the hottest days with Sirius, the Dog Star."},
    {"text": "National Dog Day is celebrated on August 26th in the United States, founded in 2004 by animal advocate Colleen Paige.", "month": 8, "day": 26},
    {"text": "The Canine Companions for Independence organization has placed over 6,500 assistance dogs since its founding in 1975."},
    {"text": "Dogs align themselves with the Earth's magnetic field when they poop — research shows they prefer to face north or south.", "type": "did-you-know"},
    {"text": "The first cloned dog, an Afghan Hound named Snuppy, was created by South Korean scientists in 2005."},
    {"text": "Dogs' paws smell like Fritos or corn chips due to natural bacteria (Pseudomonas and Proteus) on their feet — colloquially called 'Frito Feet.'", "type": "did-you-know"},
    {"text": "The Basenji and the Shiba Inu are among the most genetically similar breeds to wolves, despite their small size."},
    {"text": "Dogs can detect earthquakes before they happen — many owners report unusual behavior in the minutes before a tremor."},
    {"text": "The Iditarod race commemorates the 1925 serum run to Nome, when sled dog teams relayed diphtheria antitoxin across 674 miles of Alaskan wilderness."},
    {"text": "Dogs have been shown to understand fairness — they become upset when they see another dog rewarded for the same task they performed without reward."},

    # === DOG BREEDS — EVEN MORE ===
    {"text": "The Labradoodle was first intentionally bred in 1989 by Wally Conron for Guide Dogs Victoria in Australia, crossing a Lab with a Standard Poodle."},
    {"text": "The Goldendoodle (Golden Retriever × Poodle) became one of the most popular designer breeds due to their hypoallergenic coats and friendly temperament."},
    {"text": "The Cockapoo (Cocker Spaniel × Poodle) is considered the first 'designer dog,' dating back to the 1960s."},
    {"text": "The Puggle (Pug × Beagle) became a popular designer breed in the 2000s, combining the Pug's compact size with the Beagle's energy."},
    {"text": "The Borzoi (Russian Wolfhound) was bred by Russian aristocracy to hunt wolves — their long snout gives them a 270-degree field of vision."},
    {"text": "The Irish Setter's gorgeous red coat made it a favorite show dog, but it was originally bred as a gun dog for bird hunting."},
    {"text": "The Scottish Terrier (Scottie) is the breed most frequently associated with the Monopoly board game — the Scottie token has been in the game since 1937.", "type": "did-you-know"},
    {"text": "The Tibetan Mastiff was once used to guard monasteries in Tibet — they are among the most ancient and independent-minded breeds."},
    {"text": "The Keeshond served as the symbol of the Dutch Patriots Party in the 18th century and is named after Cornelis (Kees) de Gyselaer, a patriot leader."},
    {"text": "The Italian Greyhound is a miniature Greyhound that has been a companion dog for over 2,000 years, favored by Roman nobles."},
    {"text": "The Bull Terrier was once known as the 'White Cavalier' and was bred by James Hinks in 1850s England — Spuds MacKenzie, the 1980s Budweiser mascot, was a Bull Terrier.", "type": "did-you-know"},
    {"text": "The Pug originated in China around 400 BC and was bred as a lap dog for Chinese emperors — they were treated like royalty with their own servants."},
    {"text": "The Lhasa Apso was bred in Tibet as a watchdog for monasteries and palaces — they have keen hearing and would alert monks to approaching strangers."},
    {"text": "The Old English Sheepdog's shaggy coat originally served as insulation while herding in the English countryside."},
    {"text": "The Airedale Terrier, the largest of all terrier breeds, is known as the 'King of Terriers' and served in both World Wars."},
    {"text": "The Soft-Coated Wheaten Terrier was an all-purpose farm dog in Ireland for over 200 years before being recognized by kennel clubs."},

    # === DOGS & HUMANS ===
    {"text": "Oxytocin (the 'love hormone') increases in both dogs and humans when they gaze into each other's eyes — the same mechanism bonds human parents and infants.", "type": "did-you-know"},
    {"text": "Dog owners are 4 times more likely to meet daily exercise requirements than non-dog owners, according to the American Heart Association."},
    {"text": "Children who grow up with dogs have stronger immune systems and lower rates of allergies and asthma."},
    {"text": "Petting a dog for just 15 minutes can lower blood pressure by 10%, reduce cortisol, and increase serotonin and oxytocin."},
    {"text": "Dogs can detect the emotional state of other dogs through chemical signals — happy dogs produce different scents than stressed dogs."},
    {"text": "Dogs have evolved specific muscles around their eyes that wolves don't have, giving them the ability to make 'puppy dog eyes' — a trait that evolved through domestication.", "type": "did-you-know"},
    {"text": "Studies show that dog owners have a 24% lower risk of all-cause mortality compared to non-dog owners."},
    {"text": "Dogs mirror their owners' stress levels — a 2019 study in Scientific Reports found that cortisol levels in dogs and their owners rise and fall together."},
    {"text": "The human-dog bond is estimated to be 15,000-40,000 years old, making it the longest inter-species relationship in history."},
    {"text": "Dogs can distinguish between identical twins by scent alone, even when the twins share the same diet and live in the same house.", "type": "did-you-know"},

    # === MORE FUN FACTS ===
    {"text": "A Greyhound could beat a cheetah in a long-distance race — while cheetahs are faster in short sprints, Greyhounds can maintain 35 mph for up to 7 miles."},
    {"text": "The Beatles song 'Martha My Dear' was written by Paul McCartney about his Old English Sheepdog, Martha."},
    {"text": "In 2019, a Golden Retriever named Orca became an internet sensation after refusing to leave a lake, swimming for hours while his owner tried to call him back."},
    {"text": "The 'Good Boy/Good Girl' response in dogs triggers a dopamine release similar to what happens in humans receiving praise."},
    {"text": "French Bulldogs have become the most popular breed in major US cities like New York, Los Angeles, and San Francisco."},
    {"text": "Dogs have been taught to drive cars — New Zealand's SPCA trained rescue dogs to drive modified cars to prove their intelligence."},
    {"text": "The Canaan Dog is Israel's national breed and is one of the oldest breeds, with remains found in archaeological sites dating back 2,200 years."},
    {"text": "Dogs can learn by observation — watching another dog perform a task helps them learn it faster than trial-and-error alone."},
    {"text": "The Hungarian Puli's distinctive corded coat looks like dreadlocks and serves as protection from both weather and predators."},
    {"text": "A group of Pugs is called a 'grumble.'", "type": "did-you-know"},
    {"text": "The Azawakh, from the Sahel region of Africa, is one of the rarest breeds in Western countries and can withstand extreme heat."},
    {"text": "Dogs can be left-pawed or right-pawed — left-pawed dogs are more likely to show aggression toward strangers, according to a 2006 University of Adelaide study."},
    {"text": "Newfoundlands have literal webbed feet, making them exceptional swimmers — Lewis and Clark brought a Newfoundland named Seaman on their expedition."},
    {"text": "The Afghan Hound is thought to be one of the oldest dog breeds, with roots going back thousands of years to the mountains of Afghanistan."},
    {"text": "George Lucas modeled the Ewoks from Star Wars partly on his family dog, an Alaskan Malamute."},
    {"text": "Dogs have about 18 muscles controlling their ears, allowing them to tilt, rotate, and raise each ear independently."},
    {"text": "The 'shake it off' behavior dogs do after getting wet removes about 70% of the water from their fur in just 4 seconds.", "type": "did-you-know"},
    {"text": "A Labrador named Tubby collected over 26,000 discarded plastic bottles during his daily walks over 6 years."},
    {"text": "Dogs prefer to run into the wind because it brings them more scent information about what lies ahead."},
    {"text": "The 'play bow' — front end down, back end up — is a universal invitation to play among dogs and is understood across all breeds."},
    {"text": "Dogs have three types of hair: the undercoat (soft, insulating), the guard hairs (coarse, protective), and whiskers (sensory)."},
    {"text": "The Komondor's corded white coat was designed to help it blend in with sheep while guarding flocks from wolves and bears."},
    {"text": "A dog named Bobbie the Wonder Dog traveled 2,800 miles across the American landscape in 1923 to return to his family in Oregon after getting lost in Indiana.", "type": "did-you-know"},
    {"text": "The Kerry Blue Terrier is born with a black coat that gradually changes to its signature blue-gray color by about 18 months of age."},
    {"text": "Dogs process language using the left hemisphere of their brain (for meaning) and the right hemisphere (for intonation) — similar to humans."},
    {"text": "The American Water Spaniel is the state dog of Wisconsin and one of very few breeds developed entirely in the United States."},
    {"text": "A dog named Nesbit earned over 1 million Delta Air Lines SkyMiles by flying with his owner and became a mascot for frequent flyer dogs."},
    {"text": "Dogs' whiskers (vibrissae) are sophisticated sensory tools that detect changes in air currents, helping them navigate in low-light conditions."},
    {"text": "The Barbet, a French water dog, is one of the original breeds that contributed to the development of the Poodle."},
    {"text": "National Puppy Day is celebrated on March 23rd and was founded in 2006 to promote adoption from shelters and rescues.", "month": 3, "day": 23},
    {"text": "Dogs can suffer from seasonal allergies just like humans — symptoms include itchy skin, watery eyes, and excessive licking of paws."},
    {"text": "The Finnish Lapphund was originally bred by the Sami people to herd reindeer in the harsh Arctic conditions of Lapland."},
    {"text": "Dogs have a 'dewclaw' on the inside of their front legs — some breeds also have rear dewclaws, and the Great Pyrenees has double rear dewclaws."},
    {"text": "A dog's heart beats between 60 and 140 times per minute, depending on the size of the dog — smaller dogs have faster heart rates."},
    {"text": "The Entlebucher Mountain Dog is the smallest of the four Swiss Mountain Dog breeds and was traditionally used for herding cattle in the Swiss Alps."},
    {"text": "Dogs can have memories that last for years — they can remember people, places, and experiences from their past, especially emotionally significant ones."},
    {"text": "The Carolina Dog (American Dingo) is a free-ranging dog found in the southeastern United States that may descend from ancient Asian dogs brought by early humans.", "type": "did-you-know"},
    {"text": "The most common name for a male dog in the US is Max, while the most common female dog name is Bella."},
    {"text": "Dogs can detect bed bugs, termites, and even truffles — some trained truffle dogs can earn their owners thousands of dollars per season."},
    {"text": "The Lagotto Romagnolo from Italy is the only breed specifically bred for truffle hunting.", "type": "did-you-know"},
    {"text": "Dogs have been used to sniff out electronic storage devices in forensic investigations, detecting hidden USB drives and SD cards."},
    {"text": "The Swedish Vallhund looks like a Corgi and dates back to the time of the Vikings over 1,000 years ago."},
    {"text": "Dogs have an average gestation period of about 63 days (9 weeks)."},
    {"text": "The Chinook is the state dog of New Hampshire and is one of the rarest breeds in the world, originally bred for sled dog racing."},
    {"text": "A dog's jaws can exert 150-200 pounds of pressure per square inch — some breeds like the Kangal can exceed 700 PSI.", "type": "did-you-know"},
    {"text": "Dogs will often bring their owners their favorite toy when they notice their owner is upset — research suggests this is an empathetic response."},
    {"text": "The Portuguese Podengo is one of the oldest European breeds, used for hunting rabbits in Portugal for over 2,000 years."},
    {"text": "International Dog Day is celebrated on August 26th, founded to encourage adoption and raise awareness about dog welfare around the world.", "month": 8, "day": 26},
    {"text": "The Bolognese dog is related to the Bichon Frise and was a favorite of Italian nobility during the Renaissance."},
    {"text": "Dogs experience jealousy — a UCSD study found that dogs showed jealous behaviors when their owners interacted with a realistic stuffed dog."},
    {"text": "The Plott Hound is the state dog of North Carolina and was bred by the Plott family for over 200 years to hunt bears in the Appalachian Mountains.", "type": "did-you-know"},
    {"text": "Dogs can be trained to predict epileptic seizures up to 45 minutes before they occur, giving their owners time to prepare."},
    {"text": "The Saluki can run at speeds up to 42 mph and is considered the second-fastest dog breed after the Greyhound."},
    {"text": "Dogs have approximately 319 bones in their body, compared to 206 in adult humans."},
    {"text": "The Mudi is a rare Hungarian herding breed that can jump over 6-foot fences from a standstill."},
    {"text": "A dog named Naki'o became the first dog to receive four prosthetic legs, allowing him to run and play after losing his paws to frostbite.", "type": "did-you-know"},
]

data = {"hobby": "Dogs", "facts": facts}

path = os.path.join(os.path.dirname(__file__), '..', 'extension', 'data', 'facts', 'dogs.json')
with open(path, 'w') as f:
    json.dump(data, f, ensure_ascii=False)

print(f"Created dogs.json with {len(facts)} facts")
