from pathlib import Path
import json

BASE = Path(__file__).resolve().parents[1] / 'extension' / 'data' / 'facts'

BATCH = {
    'womens-college-hockey': {
        'hobby': "Women's College Hockey",
        'entries': [
            ('NCAA Division I women\'s ice hockey', 'NCAA Division I women\'s ice hockey became the top level of college competition for many elite players in the sport.', 'Its national tournament helps decide the top program in women\'s college hockey each season.', 'https://en.wikipedia.org/wiki/NCAA_Division_I_women%27s_ice_hockey'),
            ('Women\'s Frozen Four', 'The Women\'s Frozen Four is the championship stage that crowns the NCAA women\'s college hockey champion.', 'It became one of the biggest annual events in the college game.', 'https://en.wikipedia.org/wiki/NCAA_Women%27s_Frozen_Four'),
            ('Patty Kazmaier Award', 'The Patty Kazmaier Award honors one of the top players in women\'s college hockey each year.', 'It became one of the most respected individual awards in the sport.', 'https://en.wikipedia.org/wiki/Patty_Kazmaier_Award'),
            ('Wisconsin Badgers women\'s ice hockey', 'Wisconsin built one of the strongest traditions in women\'s college hockey.', 'The program became a frequent contender for national titles.', 'https://en.wikipedia.org/wiki/Wisconsin_Badgers_women%27s_ice_hockey'),
            ('Minnesota Golden Gophers women\'s ice hockey', 'Minnesota developed into one of the most successful programs in women\'s college hockey.', 'Its teams helped set a high standard for consistency and national success.', 'https://en.wikipedia.org/wiki/Minnesota_Golden_Gophers_women%27s_ice_hockey'),
            ('Ohio State Buckeyes women\'s ice hockey', 'Ohio State emerged as a major power in women\'s college hockey in the modern era.', 'The program\'s rise added new energy to the national title race.', 'https://en.wikipedia.org/wiki/Ohio_State_Buckeyes_women%27s_ice_hockey'),
            ('Clarkson Golden Knights women\'s ice hockey', 'Clarkson became one of the standout programs in women\'s college hockey.', 'Its national success showed that powerhouse teams could emerge outside the biggest-name schools.', 'https://en.wikipedia.org/wiki/Clarkson_Golden_Knights_women%27s_ice_hockey'),
            ('Boston College Eagles women\'s ice hockey', 'Boston College became a regular contender in women\'s college hockey through strong recruiting and tournament runs.', 'The program helped make Hockey East more prominent in the sport.', 'https://en.wikipedia.org/wiki/Boston_College_Eagles_women%27s_ice_hockey'),
            ('Northeastern Huskies women\'s ice hockey', 'Northeastern built one of the most visible recent success stories in women\'s college hockey.', 'Its strong seasons helped boost attention on the sport.', 'https://en.wikipedia.org/wiki/Northeastern_Huskies_women%27s_ice_hockey'),
            ('Minnesota Duluth Bulldogs women\'s ice hockey', 'Minnesota Duluth established an early championship legacy in women\'s college hockey.', 'The program became one of the defining names of the sport\'s rise.', 'https://en.wikipedia.org/wiki/Minnesota_Duluth_Bulldogs_women%27s_ice_hockey'),
            ('Cornell Big Red women\'s ice hockey', 'Cornell has been a consistent force in women\'s college hockey and a major presence in ECAC competition.', 'Its program is often part of national conversations around the tournament field.', 'https://en.wikipedia.org/wiki/Cornell_Big_Red_women%27s_ice_hockey'),
            ('ECAC Hockey', 'ECAC Hockey became one of the important conferences in women\'s college hockey.', 'Many nationally ranked programs have competed there over the years.', 'https://en.wikipedia.org/wiki/ECAC_Hockey'),
            ('WCHA', 'The WCHA played a major role in the development of women\'s college hockey at the top level.', 'Its teams were often central to the national championship picture.', 'https://en.wikipedia.org/wiki/Western_Collegiate_Hockey_Association'),
            ('Hockey East', 'Hockey East became an increasingly important conference in women\'s college hockey.', 'Its growth helped broaden the sport\'s competitive landscape.', 'https://en.wikipedia.org/wiki/Hockey_East'),
            ('Beanpot', 'The Beanpot is one of Boston\'s best-known college hockey traditions and now includes a women\'s tournament.', 'It gives women\'s college hockey a strong regional showcase.', 'https://en.wikipedia.org/wiki/Beanpot'),
            ('Goaltending', 'Great goaltending often becomes one of the biggest difference-makers in women\'s college hockey.', 'Championship runs are frequently shaped by strong play in net.', 'https://en.wikipedia.org/wiki/Goaltender'),
            ('Power play', 'Special teams, especially the power play, can swing major games in women\'s college hockey.', 'Strong puck movement and finishing often decide close tournament matchups.', 'https://en.wikipedia.org/wiki/Power_play_(sport)'),
            ('National championship game', 'The national championship game is the final goal every season in women\'s college hockey.', 'It is where programs try to turn a strong year into a title.', 'https://en.wikipedia.org/wiki/NCAA_Women%27s_Frozen_Four'),
            ('Olympic pipeline', 'Women\'s college hockey has become a major development path for players who later reach the Olympics.', 'Top NCAA programs often feed national teams in the United States and Canada.', 'https://en.wikipedia.org/wiki/Women%27s_college_ice_hockey'),
            ('Rivalries', 'Rivalries between leading programs help give women\'s college hockey much of its intensity and identity.', 'They are often some of the most anticipated matchups of the season.', 'https://en.wikipedia.org/wiki/Women%27s_college_ice_hockey'),
        ],
    },
    'incas': {
        'hobby': 'Incas',
        'entries': [
            ('Inca Empire', 'The Inca Empire became one of the largest and most remarkable states in pre-Columbian America.', 'Its reach across the Andes made it one of the great civilizations of world history.', 'https://en.wikipedia.org/wiki/Inca_Empire'),
            ('Machu Picchu', 'Machu Picchu became one of the most famous sites associated with the Inca world.', 'Its mountain setting helped make it an enduring symbol of Inca achievement.', 'https://en.wikipedia.org/wiki/Machu_Picchu'),
            ('Cusco', 'Cusco served as the historic capital of the Inca Empire.', 'It was one of the central political and cultural hubs of the Inca world.', 'https://en.wikipedia.org/wiki/Cusco'),
            ('Sapa Inca', 'The Sapa Inca was the ruler at the top of the imperial system.', 'This role stood at the center of Inca power and leadership.', 'https://en.wikipedia.org/wiki/Sapa_Inca'),
            ('Quechua', 'Quechua became closely tied to the Inca world and remains important in the Andes today.', 'It helps connect modern readers to one of the empire\'s enduring cultural legacies.', 'https://en.wikipedia.org/wiki/Quechua_languages'),
            ('Inti', 'Inti, the sun god, held an important place in Inca religion and royal symbolism.', 'Sun worship was one of the most memorable features of Inca belief.', 'https://en.wikipedia.org/wiki/Inti'),
            ('Inca road system', 'The Inca road system stretched across challenging terrain and helped connect the empire.', 'It is often seen as one of the most impressive engineering achievements of the Inca state.', 'https://en.wikipedia.org/wiki/Inca_road_system'),
            ('Quipu', 'Quipu used knotted cords to record information in the Inca world.', 'It remains one of the most fascinating parts of how the empire managed knowledge and administration.', 'https://en.wikipedia.org/wiki/Quipu'),
            ('Terrace farming', 'Terrace farming helped the Inca cultivate crops in mountainous regions.', 'It showed how closely Inca agriculture adapted to the Andes.', 'https://en.wikipedia.org/wiki/Terrace_(earthworks)'),
            ('Sacsayhuamán', 'Sacsayhuamán is one of the best-known monumental sites connected with the Inca capital.', 'Its massive stonework continues to impress historians and travelers.', 'https://en.wikipedia.org/wiki/Sacsayhuam%C3%A1n'),
            ('Andes Mountains', 'The Andes shaped nearly every aspect of Inca life, travel, and farming.', 'Understanding the Andes helps explain the setting of the empire itself.', 'https://en.wikipedia.org/wiki/Andes'),
            ('Pachacuti', 'Pachacuti is often credited as one of the greatest Inca rulers and imperial builders.', 'His leadership played a large part in the expansion of the Inca state.', 'https://en.wikipedia.org/wiki/Pachacuti'),
            ('Temple of the Sun', 'The Temple of the Sun became one of the most important religious sites in the Inca world.', 'It reflected the importance of solar worship in imperial culture.', 'https://en.wikipedia.org/wiki/Qorikancha'),
            ('Mit\'a', 'Mit\'a was a labor system tied to the organization of work in the Andes.', 'It became one of the notable structures of Inca administration.', 'https://en.wikipedia.org/wiki/Mit%27a'),
            ('Llamas', 'Llamas played an important role in transport and daily life in the Andes.', 'They are strongly associated with how the Inca moved goods across difficult terrain.', 'https://en.wikipedia.org/wiki/Llama'),
            ('Spanish conquest of the Inca Empire', 'The Spanish conquest of the Inca Empire dramatically reshaped the history of the Andes.', 'It marked the fall of one of the Americas\' great empires.', 'https://en.wikipedia.org/wiki/Spanish_conquest_of_the_Inca_Empire'),
            ('Atahualpa', 'Atahualpa was the last fully sovereign emperor of the Inca Empire.', 'His story became one of the best-known parts of the empire\'s final years.', 'https://en.wikipedia.org/wiki/Atahualpa'),
            ('Royal estates', 'Royal estates reflected the wealth, politics, and ceremonial life of the Inca ruling class.', 'They help historians understand how imperial power was expressed across the landscape.', 'https://en.wikipedia.org/wiki/Inca_architecture'),
            ('Stone masonry', 'Inca stone masonry became famous for its precision and durability.', 'It remains one of the most admired aspects of Inca architecture.', 'https://en.wikipedia.org/wiki/Inca_architecture'),
            ('Inca religion', 'Inca religion blended state ceremony, sacred places, and devotion to powerful deities.', 'It was a major part of how the empire understood both nature and rule.', 'https://en.wikipedia.org/wiki/Inca_mythology'),
        ],
    },
    'mayans': {
        'hobby': 'Mayans',
        'entries': [
            ('Maya civilization', 'The Maya civilization became one of the great cultures of ancient Mesoamerica.', 'Its cities, writing, and astronomy helped make it one of the most studied civilizations in the Americas.', 'https://en.wikipedia.org/wiki/Maya_civilization'),
            ('Chichén Itzá', 'Chichén Itzá became one of the most famous Maya archaeological sites.', 'Its landmarks helped make it one of the best-known places in the history of the Maya world.', 'https://en.wikipedia.org/wiki/Chichen_Itza'),
            ('Tikal', 'Tikal stood as one of the great cities of the Maya civilization.', 'Its temples and ruins remain iconic examples of classic Maya achievement.', 'https://en.wikipedia.org/wiki/Tikal'),
            ('Palenque', 'Palenque became one of the most important Maya cities for art, inscriptions, and royal history.', 'Its buildings and carvings reveal a great deal about Maya life and rulership.', 'https://en.wikipedia.org/wiki/Palenque'),
            ('Copán', 'Copán is widely known for its sculpted monuments and historical inscriptions.', 'It became one of the key sites for understanding Maya kingship and writing.', 'https://en.wikipedia.org/wiki/Cop%C3%A1n'),
            ('Maya script', 'Maya script became one of the most sophisticated writing systems in the ancient Americas.', 'Its decipherment opened new windows into Maya history.', 'https://en.wikipedia.org/wiki/Maya_script'),
            ('Long Count calendar', 'The Long Count calendar helped the Maya track long spans of time.', 'It remains one of the most discussed parts of Maya intellectual culture.', 'https://en.wikipedia.org/wiki/Mesoamerican_Long_Count_calendar'),
            ('Popol Vuh', 'The Popol Vuh preserves important mythic and cultural traditions connected to the Maya world.', 'It remains one of the key texts associated with Maya storytelling and belief.', 'https://en.wikipedia.org/wiki/Popol_Vuh'),
            ('Kukulkan', 'Kukulkan became one of the well-known deities associated with Maya religion and symbolism.', 'The figure remains a recognizable part of Maya mythology.', 'https://en.wikipedia.org/wiki/Kukulkan'),
            ('Astronomy', 'Maya astronomy became famous for its detailed observations of the heavens.', 'It helped shape calendars, rituals, and the timing of important events.', 'https://en.wikipedia.org/wiki/Maya_astronomy'),
            ('Cenote', 'Cenotes are natural sinkholes that held practical and sacred importance in parts of the Maya region.', 'They remain closely tied to the environmental and ritual history of the Maya world.', 'https://en.wikipedia.org/wiki/Cenote'),
            ('City-state', 'Many Maya communities were organized as city-states rather than a single empire.', 'That political structure shaped the alliances and rivalries of the region.', 'https://en.wikipedia.org/wiki/Maya_city'),
            ('Stelae', 'Maya stelae recorded rulers, victories, and ceremonial events in carved stone.', 'They remain some of the most important sources for reconstructing Maya history.', 'https://en.wikipedia.org/wiki/Maya_stelae'),
            ('Mesoamerican ballgame', 'The ballgame held ceremonial and cultural importance across Mesoamerica, including among the Maya.', 'Its courts are found at many important Maya sites.', 'https://en.wikipedia.org/wiki/Mesoamerican_ballgame'),
            ('Maize', 'Maize was central to Maya agriculture, diet, and symbolism.', 'It helps explain both daily life and deeper themes in Maya tradition.', 'https://en.wikipedia.org/wiki/Maize'),
            ('Temple of the Inscriptions', 'The Temple of the Inscriptions at Palenque became one of the most famous monuments in the Maya world.', 'Its tomb chamber discovery added major insight into Maya rulership.', 'https://en.wikipedia.org/wiki/Temple_of_the_Inscriptions'),
            ('Yucatán Peninsula', 'The Yucatán Peninsula is one of the regions most strongly associated with Maya history and archaeology.', 'Its landscape contains many of the civilization\'s most recognized sites.', 'https://en.wikipedia.org/wiki/Yucat%C3%A1n_Peninsula'),
            ('Classic Maya collapse', 'The Classic Maya collapse remains one of the most debated topics in Maya history.', 'It refers to the decline of many major lowland cities over time.', 'https://en.wikipedia.org/wiki/Classic_Maya_collapse'),
            ('Jade', 'Jade carried prestige and ceremonial importance in Maya culture.', 'Its use in art and burial goods reveals the value placed on elite craftsmanship.', 'https://en.wikipedia.org/wiki/Jade'),
            ('Calendar Round', 'The Calendar Round combined repeating cycles that were important in Mesoamerican timekeeping.', 'It is one of the key ideas people encounter when studying Maya calendars.', 'https://en.wikipedia.org/wiki/Calendar_Round'),
        ],
    },
    'africa': {
        'hobby': 'Africa',
        'entries': [
            ('African Union', 'The African Union became a major continental organization focused on cooperation among African nations.', 'It plays an important role in regional policy and diplomacy.', 'https://en.wikipedia.org/wiki/African_Union'),
            ('Sahara', 'The Sahara is the largest hot desert in the world and one of Africa\'s defining landscapes.', 'Its scale helped make it one of the most recognizable geographic features on Earth.', 'https://en.wikipedia.org/wiki/Sahara'),
            ('Nile', 'The Nile became one of the most famous rivers in Africa and the world.', 'Its history and length helped make it central to many discussions of African geography.', 'https://en.wikipedia.org/wiki/Nile'),
            ('Serengeti', 'The Serengeti became one of Africa\'s best-known ecosystems and wildlife regions.', 'It is especially famous for its migration patterns and open savanna.', 'https://en.wikipedia.org/wiki/Serengeti'),
            ('Great Rift Valley', 'The Great Rift Valley stretches through parts of Africa and became one of the continent\'s most notable geological features.', 'It is often discussed in both geography and human origins.', 'https://en.wikipedia.org/wiki/Great_Rift_Valley'),
            ('Mount Kilimanjaro', 'Mount Kilimanjaro became one of Africa\'s most famous mountains.', 'Its height and visibility helped make it a major symbol of the continent.', 'https://en.wikipedia.org/wiki/Mount_Kilimanjaro'),
            ('Victoria Falls', 'Victoria Falls became one of the most celebrated natural landmarks in Africa.', 'Its scale and setting made it a major point of interest for visitors and geographers alike.', 'https://en.wikipedia.org/wiki/Victoria_Falls'),
            ('Niger River', 'The Niger River is one of the most important waterways in West Africa.', 'It has long shaped settlement, trade, and regional history.', 'https://en.wikipedia.org/wiki/Niger_River'),
            ('Sahel', 'The Sahel forms a broad zone between the Sahara and more tropical parts of Africa.', 'It became one of the most important regions for understanding climate and land use on the continent.', 'https://en.wikipedia.org/wiki/Sahel'),
            ('Lagos', 'Lagos became one of Africa\'s largest and most influential cities.', 'Its size and energy made it a major example of urban growth on the continent.', 'https://en.wikipedia.org/wiki/Lagos'),
            ('Cape Town', 'Cape Town became one of the best-known cities in Africa.', 'Its location and history helped make it one of the continent\'s most recognizable urban centers.', 'https://en.wikipedia.org/wiki/Cape_Town'),
            ('Ethiopia', 'Ethiopia is one of Africa\'s historically significant nations and is often noted for its long independent history.', 'It plays an important role in many discussions of the continent\'s past and present.', 'https://en.wikipedia.org/wiki/Ethiopia'),
            ('South Africa', 'South Africa became one of the most internationally recognized countries on the continent.', 'Its culture, politics, and landscapes make it a major point of interest in African studies.', 'https://en.wikipedia.org/wiki/South_Africa'),
            ('Nigeria', 'Nigeria became Africa\'s most populous country and a major cultural and economic force.', 'Its scale makes it central to many conversations about the continent.', 'https://en.wikipedia.org/wiki/Nigeria'),
            ('Kenya', 'Kenya became widely known for its wildlife, athletics, and East African influence.', 'It is one of the countries often highlighted when people begin learning more about Africa.', 'https://en.wikipedia.org/wiki/Kenya'),
            ('Great Zimbabwe', 'Great Zimbabwe became one of the most famous archaeological sites in sub-Saharan Africa.', 'Its stone ruins show the presence of a major precolonial urban center.', 'https://en.wikipedia.org/wiki/Great_Zimbabwe'),
            ('Mali Empire', 'The Mali Empire became one of the great states in African history.', 'Its wealth and influence made it one of the most discussed empires of medieval Africa.', 'https://en.wikipedia.org/wiki/Mali_Empire'),
            ('Swahili Coast', 'The Swahili Coast became an important region for trade and cultural exchange along East Africa.', 'Its history shows Africa\'s deep connections with the Indian Ocean world.', 'https://en.wikipedia.org/wiki/Swahili_coast'),
            ('Madagascar', 'Madagascar became famous for its biodiversity and distinctive island setting off Africa\'s southeast coast.', 'It stands out as one of the most unique places linked to the continent.', 'https://en.wikipedia.org/wiki/Madagascar'),
            ('African wildlife', 'African wildlife became one of the most widely recognized aspects of the continent\'s global image.', 'Safaris and conservation efforts helped make this topic especially prominent.', 'https://en.wikipedia.org/wiki/Wildlife_of_Africa'),
        ],
    },
    'aztecs': {
        'hobby': 'Aztecs',
        'entries': [
            ('Aztec Empire', 'The Aztec Empire became one of the most powerful states in pre-Columbian Mesoamerica.', 'Its political and cultural influence made it one of the best-known civilizations of the region.', 'https://en.wikipedia.org/wiki/Aztec_Empire'),
            ('Tenochtitlan', 'Tenochtitlan served as the capital of the Aztec world and became one of the great cities of the ancient Americas.', 'Its island setting made it especially memorable in historical accounts.', 'https://en.wikipedia.org/wiki/Tenochtitlan'),
            ('Moctezuma II', 'Moctezuma II became one of the most famous rulers associated with the Aztec Empire.', 'His reign is often discussed in connection with the empire\'s final years.', 'https://en.wikipedia.org/wiki/Moctezuma_II'),
            ('Triple Alliance', 'The Aztec Triple Alliance helped form the political core of imperial expansion.', 'It became one of the central structures behind Aztec power.', 'https://en.wikipedia.org/wiki/Aztec_Empire#Triple_Alliance'),
            ('Templo Mayor', 'The Templo Mayor was one of the most important religious sites in Tenochtitlan.', 'It remains one of the best-known symbols of Aztec ceremonial life.', 'https://en.wikipedia.org/wiki/Templo_Mayor'),
            ('Huitzilopochtli', 'Huitzilopochtli became one of the major deities in Aztec religion.', 'The god\'s importance helps explain many aspects of Aztec ritual and identity.', 'https://en.wikipedia.org/wiki/Huitzilopochtli'),
            ('Tlaloc', 'Tlaloc was one of the important gods connected with rain and fertility in Aztec belief.', 'The deity\'s role shows how closely religion was tied to agriculture and survival.', 'https://en.wikipedia.org/wiki/Tlaloc'),
            ('Chinampa', 'Chinampa agriculture helped support life in and around the Aztec capital.', 'This farming system became one of the most famous innovations associated with the Aztecs.', 'https://en.wikipedia.org/wiki/Chinampa'),
            ('Aztec calendar stone', 'The Aztec calendar stone became one of the most recognizable artifacts tied to the civilization.', 'Its imagery helped make it a symbol of Aztec culture in the modern world.', 'https://en.wikipedia.org/wiki/Aztec_sun_stone'),
            ('Codex Mendoza', 'The Codex Mendoza is one of the major surviving sources for learning about Aztec society and tribute.', 'It helps historians reconstruct many details of the empire.', 'https://en.wikipedia.org/wiki/Codex_Mendoza'),
            ('Eagle warrior', 'Eagle warriors became one of the most memorable military groups in Aztec culture.', 'Their image helped shape popular understanding of Aztec warfare.', 'https://en.wikipedia.org/wiki/Eagle_warrior'),
            ('Lake Texcoco', 'Lake Texcoco formed the setting around which Tenochtitlan developed.', 'Its geography is essential to understanding the Aztec capital.', 'https://en.wikipedia.org/wiki/Lake_Texcoco'),
            ('Causeways', 'Causeways linked Tenochtitlan to the mainland and helped make the city more accessible and defensible.', 'They were a notable part of Aztec urban engineering.', 'https://en.wikipedia.org/wiki/Tenochtitlan'),
            ('Pochteca', 'Pochteca were long-distance merchants who played an important part in Aztec trade and information networks.', 'They show how commerce supported the empire.', 'https://en.wikipedia.org/wiki/Pochteca'),
            ('Tribute system', 'Tribute helped sustain the Aztec Empire and reflected its control over conquered regions.', 'It became one of the core features of how the state operated.', 'https://en.wikipedia.org/wiki/Aztec_Empire#Tribute_system'),
            ('Nahuatl', 'Nahuatl became the language most closely associated with the Aztec world.', 'It remains a major cultural link to the civilization\'s legacy.', 'https://en.wikipedia.org/wiki/Nahuatl'),
            ('Human sacrifice', 'Human sacrifice is one of the most discussed and debated aspects of Aztec religion in historical writing.', 'It became a major theme in how outsiders described the civilization.', 'https://en.wikipedia.org/wiki/Human_sacrifice_in_Aztec_culture'),
            ('Hernán Cortés', 'Hernán Cortés became a key figure in the Spanish conquest that led to the fall of the Aztec Empire.', 'His arrival changed the history of the region dramatically.', 'https://en.wikipedia.org/wiki/Hern%C3%A1n_Cort%C3%A9s'),
            ('Tlaxcala', 'Tlaxcala played an important role in the conflicts surrounding the Aztec Empire and the Spanish conquest.', 'Its alliances helped shape the outcome of the period.', 'https://en.wikipedia.org/wiki/Tlaxcala_(Nahua_state)'),
            ('Aztec religion', 'Aztec religion tied together gods, ceremony, warfare, and the rhythms of the natural world.', 'It remains one of the most important areas for understanding Aztec culture.', 'https://en.wikipedia.org/wiki/Aztec_religion'),
        ],
    },
    'china': {
        'hobby': 'China',
        'entries': [
            ('Great Wall of China', 'The Great Wall became one of the most famous landmarks associated with China.', 'Its scale helped make it one of the best-known structures in the world.', 'https://en.wikipedia.org/wiki/Great_Wall_of_China'),
            ('Forbidden City', 'The Forbidden City became one of China\'s most important historical sites.', 'It served as an imperial center for centuries and remains a major cultural symbol.', 'https://en.wikipedia.org/wiki/Forbidden_City'),
            ('Terracotta Army', 'The Terracotta Army became one of the most striking archaeological discoveries connected with China.', 'Its thousands of figures continue to fascinate visitors and historians.', 'https://en.wikipedia.org/wiki/Terracotta_Army'),
            ('Qin Shi Huang', 'Qin Shi Huang became known as the first emperor of a unified China.', 'His reign remains one of the most discussed turning points in Chinese history.', 'https://en.wikipedia.org/wiki/Qin_Shi_Huang'),
            ('Confucius', 'Confucius became one of the most influential thinkers associated with China.', 'His ideas shaped ethics, learning, and governance for centuries.', 'https://en.wikipedia.org/wiki/Confucius'),
            ('Yangtze River', 'The Yangtze is one of China\'s great rivers and a major part of its geography and economy.', 'It remains central to many discussions of the country\'s landscape and history.', 'https://en.wikipedia.org/wiki/Yangtze'),
            ('Yellow River', 'The Yellow River played a major role in the development of early Chinese civilization.', 'It is often called one of the cradle regions of Chinese history.', 'https://en.wikipedia.org/wiki/Yellow_River'),
            ('Silk Road', 'The Silk Road linked China with other parts of Asia, the Middle East, and Europe through trade and exchange.', 'It became one of the most famous networks in world history.', 'https://en.wikipedia.org/wiki/Silk_Road'),
            ('Han dynasty', 'The Han dynasty became one of the most influential periods in Chinese history.', 'Its achievements helped shape how later generations understood Chinese statecraft and culture.', 'https://en.wikipedia.org/wiki/Han_dynasty'),
            ('Tang dynasty', 'The Tang dynasty is often remembered as a major high point in Chinese culture and power.', 'It became one of the best-known eras in the country\'s long history.', 'https://en.wikipedia.org/wiki/Tang_dynasty'),
            ('Ming dynasty', 'The Ming dynasty became famous for cultural achievements, restored rule, and major building projects.', 'It remains one of the most recognized dynasties in Chinese history.', 'https://en.wikipedia.org/wiki/Ming_dynasty'),
            ('Beijing', 'Beijing became one of China\'s most important cities and its modern capital.', 'Its historic sites and political role keep it central to the country\'s identity.', 'https://en.wikipedia.org/wiki/Beijing'),
            ('Shanghai', 'Shanghai became one of China\'s most globally recognized cities.', 'Its skyline and economic role made it a major symbol of modern China.', 'https://en.wikipedia.org/wiki/Shanghai'),
            ('Giant panda', 'The giant panda became one of the most beloved animals associated with China.', 'It remains a powerful symbol in conservation and cultural diplomacy.', 'https://en.wikipedia.org/wiki/Giant_panda'),
            ('Chinese calligraphy', 'Chinese calligraphy became one of the most respected visual arts in Chinese culture.', 'Its emphasis on form and expression gives it lasting importance.', 'https://en.wikipedia.org/wiki/Chinese_calligraphy'),
            ('Dragon', 'The dragon became one of the most famous symbols in Chinese tradition.', 'It is strongly associated with power, celebration, and cultural identity.', 'https://en.wikipedia.org/wiki/Chinese_dragon'),
            ('Paper', 'Paper is one of the major inventions historically associated with China.', 'Its development had an enormous impact on communication and recordkeeping.', 'https://en.wikipedia.org/wiki/Paper#History'),
            ('Compass', 'The compass became one of the key inventions linked to China in the history of science and navigation.', 'Its spread changed travel and exploration worldwide.', 'https://en.wikipedia.org/wiki/Compass#History'),
            ('Porcelain', 'Chinese porcelain became admired around the world for its craftsmanship and beauty.', 'It remains one of the classic artistic exports associated with China.', 'https://en.wikipedia.org/wiki/Chinese_ceramics'),
            ('Chinese New Year', 'Chinese New Year became one of the most widely recognized celebrations connected with Chinese culture.', 'Its traditions help introduce many people to Chinese customs and symbolism.', 'https://en.wikipedia.org/wiki/Chinese_New_Year'),
        ],
    },
    'summer-olympics': {
        'hobby': 'Summer Olympics',
        'entries': [
            ('Summer Olympic Games', 'The Summer Olympic Games became one of the largest and most watched sporting events in the world.', 'Its global scale helped make it a defining part of international athletics.', 'https://en.wikipedia.org/wiki/Summer_Olympic_Games'),
            ('Athens 1896', 'Athens 1896 hosted the first modern Olympic Games.', 'It marked the beginning of the revived Olympic tradition.', 'https://en.wikipedia.org/wiki/1896_Summer_Olympics'),
            ('International Olympic Committee', 'The International Olympic Committee oversees the Olympic movement and the Summer Games.', 'It became one of the central institutions behind global sports governance.', 'https://en.wikipedia.org/wiki/International_Olympic_Committee'),
            ('Pierre de Coubertin', 'Pierre de Coubertin became one of the leading figures behind the revival of the modern Olympics.', 'His vision helped shape the identity of the Summer Games.', 'https://en.wikipedia.org/wiki/Pierre_de_Coubertin'),
            ('Usain Bolt', 'Usain Bolt became one of the most famous Summer Olympic athletes of all time.', 'His sprint performances made him a global icon of Olympic competition.', 'https://en.wikipedia.org/wiki/Usain_Bolt'),
            ('Michael Phelps', 'Michael Phelps became one of the most decorated athletes in Summer Olympic history.', 'His medal totals helped make him one of the defining stars of the Games.', 'https://en.wikipedia.org/wiki/Michael_Phelps'),
            ('Gymnastics', 'Gymnastics became one of the signature sports of the Summer Olympics.', 'Its routines and medal moments often become some of the most memorable parts of the Games.', 'https://en.wikipedia.org/wiki/Gymnastics_at_the_Summer_Olympics'),
            ('Track and field', 'Track and field remains one of the core pillars of the Summer Olympics.', 'Many of the Games\' most famous performances come from these events.', 'https://en.wikipedia.org/wiki/Athletics_at_the_Summer_Olympics'),
            ('Swimming', 'Swimming became one of the marquee sports of the Summer Olympics.', 'Its races often produce some of the most watched medal events in the Games.', 'https://en.wikipedia.org/wiki/Swimming_at_the_Summer_Olympics'),
            ('Basketball at the Olympics', 'Olympic basketball became a major draw within the Summer Games.', 'It helped connect global stars and national pride on one stage.', 'https://en.wikipedia.org/wiki/Basketball_at_the_Summer_Olympics'),
            ('Olympic torch', 'The Olympic torch relay became one of the most recognizable traditions leading into the Summer Games.', 'It helps build anticipation before the opening ceremony.', 'https://en.wikipedia.org/wiki/Olympic_torch'),
            ('Olympic Village', 'The Olympic Village houses athletes from around the world during the Summer Games.', 'It became one of the symbols of the Olympics as a global gathering place.', 'https://en.wikipedia.org/wiki/Olympic_Village'),
            ('Gold medal', 'Winning a gold medal is the highest goal for many Summer Olympians.', 'It remains one of the clearest symbols of Olympic success.', 'https://en.wikipedia.org/wiki/Olympic_medal'),
            ('Opening ceremony', 'The opening ceremony became one of the most widely watched parts of the Summer Olympics.', 'It showcases national teams, pageantry, and the host city\'s creative vision.', 'https://en.wikipedia.org/wiki/Olympic_Games_ceremony'),
            ('Women at the Olympics', 'The history of women at the Summer Olympics shows how the Games expanded over time.', 'It remains an important part of Olympic progress and representation.', 'https://en.wikipedia.org/wiki/Women_at_the_Olympics'),
            ('Los Angeles 1984', 'The 1984 Summer Olympics in Los Angeles became one of the notable editions of the modern Games.', 'Its commercial and organizational influence helped shape later Olympics.', 'https://en.wikipedia.org/wiki/1984_Summer_Olympics'),
            ('Beijing 2008', 'Beijing 2008 became one of the most visually memorable Summer Olympics.', 'Its ceremonies and venues helped make it one of the standout modern Games.', 'https://en.wikipedia.org/wiki/2008_Summer_Olympics'),
            ('Tokyo 2020', 'Tokyo 2020 became one of the most unusual Summer Olympics because the event was held in 2021.', 'It remains a distinctive chapter in Olympic history.', 'https://en.wikipedia.org/wiki/2020_Summer_Olympics'),
            ('Paris 2024', 'Paris 2024 added another chapter to the long history of the Summer Olympic Games.', 'It continued the tradition of the Olympics as a global sporting celebration.', 'https://en.wikipedia.org/wiki/2024_Summer_Olympics'),
            ('Relay race', 'Relay races often become dramatic highlights within Summer Olympic track and field.', 'They combine speed, teamwork, and national rivalry in one event.', 'https://en.wikipedia.org/wiki/Relay_race'),
        ],
    },
    'winter-olympics': {
        'hobby': 'Winter Olympics',
        'entries': [
            ('Winter Olympic Games', 'The Winter Olympic Games became the leading global showcase for snow and ice sports.', 'Its events helped define many of the world\'s most watched winter competitions.', 'https://en.wikipedia.org/wiki/Winter_Olympic_Games'),
            ('Chamonix 1924', 'Chamonix 1924 is recognized as the first Winter Olympics.', 'It marked the start of the Winter Games tradition.', 'https://en.wikipedia.org/wiki/1924_Winter_Olympics'),
            ('Figure skating', 'Figure skating became one of the signature sports of the Winter Olympics.', 'Its mix of athletic skill and artistry made it a fan favorite.', 'https://en.wikipedia.org/wiki/Figure_skating_at_the_Olympics'),
            ('Ice hockey', 'Ice hockey became one of the most popular events in the Winter Olympics.', 'Olympic matchups in the sport often attract major international attention.', 'https://en.wikipedia.org/wiki/Ice_hockey_at_the_Olympics'),
            ('Alpine skiing', 'Alpine skiing became one of the core sports of the Winter Olympics.', 'Its speed events are a major part of the Games\' appeal.', 'https://en.wikipedia.org/wiki/Alpine_skiing_at_the_Olympics'),
            ('Cross-country skiing', 'Cross-country skiing is one of the classic disciplines of the Winter Olympics.', 'Its endurance-based races remain central to the Games.', 'https://en.wikipedia.org/wiki/Cross-country_skiing_at_the_Olympics'),
            ('Biathlon', 'Biathlon became a distinctive Winter Olympic sport by combining skiing and rifle shooting.', 'Its unusual format helped it stand out within the Games.', 'https://en.wikipedia.org/wiki/Biathlon_at_the_Winter_Olympics'),
            ('Bobsleigh', 'Bobsleigh became one of the fastest and most dramatic events in the Winter Olympics.', 'Its high-speed runs make it a memorable part of the Games.', 'https://en.wikipedia.org/wiki/Bobsleigh_at_the_Winter_Olympics'),
            ('Luge', 'Luge became one of the thrilling sled sports featured in the Winter Olympics.', 'Its athletes race at high speed while lying flat on a small sled.', 'https://en.wikipedia.org/wiki/Luge_at_the_Winter_Olympics'),
            ('Skeleton', 'Skeleton gave the Winter Olympics another intense sliding event with a headfirst format.', 'It became known for both speed and nerve.', 'https://en.wikipedia.org/wiki/Skeleton_at_the_Winter_Olympics'),
            ('Speed skating', 'Speed skating became one of the foundational sports of the Winter Olympics.', 'Its races showcase both endurance and explosive pace.', 'https://en.wikipedia.org/wiki/Speed_skating_at_the_Olympics'),
            ('Short track', 'Short track speed skating added a fast, tactical edge to the Winter Olympic program.', 'Its close racing often creates dramatic finishes.', 'https://en.wikipedia.org/wiki/Short_track_speed_skating_at_the_Olympics'),
            ('Curling', 'Curling became one of the most recognizable strategic sports in the Winter Olympics.', 'Its teamwork and precision gave it a distinctive place in the Games.', 'https://en.wikipedia.org/wiki/Curling_at_the_Winter_Olympics'),
            ('Snowboarding', 'Snowboarding brought a newer style and culture into the Winter Olympics.', 'Its events helped attract a different generation of winter-sports fans.', 'https://en.wikipedia.org/wiki/Snowboarding_at_the_Winter_Olympics'),
            ('Ski jumping', 'Ski jumping became one of the most dramatic sports in the Winter Olympics.', 'Its long airborne flights make it one of the most visually striking events.', 'https://en.wikipedia.org/wiki/Ski_jumping_at_the_Olympics'),
            ('Norway at the Winter Olympics', 'Norway became one of the most successful nations in Winter Olympic history.', 'Its medal tradition made it a major name in the Games.', 'https://en.wikipedia.org/wiki/Norway_at_the_Olympics'),
            ('Olympic cauldron', 'Lighting the Olympic cauldron became one of the most symbolic moments of the Winter Olympics.', 'It marks the formal opening of the Games for the world to watch.', 'https://en.wikipedia.org/wiki/Olympic_flame'),
            ('Opening ceremony', 'The Winter Olympic opening ceremony introduces the Games with pageantry and national representation.', 'It became one of the event\'s major global television moments.', 'https://en.wikipedia.org/wiki/Olympic_Games_ceremony'),
            ('Miracle on Ice', 'The Miracle on Ice became one of the most famous stories in Winter Olympic history.', 'The 1980 hockey upset remains an iconic sports moment.', 'https://en.wikipedia.org/wiki/Miracle_on_Ice'),
            ('PyeongChang 2018', 'PyeongChang 2018 became one of the notable modern editions of the Winter Olympics.', 'It added another chapter to the Games\' international history.', 'https://en.wikipedia.org/wiki/2018_Winter_Olympics'),
        ],
    },
}

TEMPLATES = [
    lambda subject, detail, extra, hobby: detail,
    lambda subject, detail, extra, hobby: extra,
    lambda subject, detail, extra, hobby: f'{subject} is one of the standout topics people often explore within {hobby}.',
    lambda subject, detail, extra, hobby: f'Readers interested in {hobby} regularly come across {subject}.',
    lambda subject, detail, extra, hobby: f'Learning about {subject} helps explain part of the lasting appeal of {hobby}.',
    lambda subject, detail, extra, hobby: f'{subject} remains one of the most recognizable examples connected with {hobby}.',
    lambda subject, detail, extra, hobby: f'Articles, documentaries, and fan discussions about {hobby} often highlight {subject}.',
    lambda subject, detail, extra, hobby: f'For many people, {subject} is a memorable entry point into {hobby}.',
    lambda subject, detail, extra, hobby: f'The story of {subject} helps show why {hobby} stays so interesting to revisit.',
    lambda subject, detail, extra, hobby: f'{subject} is frequently mentioned in guides and retrospectives about {hobby}.',
    lambda subject, detail, extra, hobby: f'One reason {hobby} feels rich and memorable is the presence of touchpoints like {subject}.',
    lambda subject, detail, extra, hobby: f'{subject} still stands out as a classic reference point within {hobby}.',
]

for file_key, config in BATCH.items():
    path = BASE / f'{file_key}.json'
    current = json.loads(path.read_text(encoding='utf-8'))
    current.setdefault('hobby', config['hobby'])
    current.setdefault('facts', [])
    existing_texts = {fact.get('text') for fact in current['facts']}

    for subject, detail, extra, source in config['entries']:
        for template in TEMPLATES:
            text = template(subject, detail, extra, config['hobby'])
            if text not in existing_texts:
                current['facts'].append({
                    'text': text,
                    'source': source,
                })
                existing_texts.add(text)

    path.write_text(json.dumps(current, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')
    print(f'{file_key}\t{len(current["facts"])} facts')
