#!/usr/bin/env python3
"""Add more facts to dogs.json to bring total above 366."""
import json

path = 'extension/data/facts/dogs.json'
with open(path) as f:
    data = json.load(f)

extra = [
    {"text": "The Chinook once nearly went extinct — in 1965 there were only 125 known Chinooks in the world."},
    {"text": "Dogs have individual bark 'accents' — researchers found that London dogs barked differently from Liverpool dogs.", "type": "did-you-know"},
    {"text": "The Stabyhoun from the Netherlands is one of the rarest dog breeds, with fewer than 7,000 in existence."},
    {"text": "A guide dog named Orient helped his blind owner Bill Irwin become the first blind person to hike the entire Appalachian Trail in 1990."},
    {"text": "The Bracco Italiano is one of the oldest pointing breeds, with depictions dating back to the 4th century BC."},
    {"text": "In ancient China, Pekingese were so prized that stealing one was punishable by death.", "type": "did-you-know"},
    {"text": "The Dutch Shepherd is an all-purpose farm dog that was nearly extinct by the 1950s but has been revived for police work."},
    {"text": "Dogs can detect changes in barometric pressure before a storm, which is why many dogs become anxious before thunderstorms."},
    {"text": "The Telomian is one of the few breeds that can climb — aboriginals in Malaysia bred them to live in stilted houses."},
    {"text": "A Border Collie named Striker holds the Guinness World Record for the fastest car window opened by a dog: 11.34 seconds."},
    {"text": "The Schipperke is Belgian and its name means 'little captain' — bred as watchdogs on canal boats.", "type": "did-you-know"},
    {"text": "Dogs produce about half a liter of saliva per day."},
    {"text": "The Dandie Dinmont Terrier is the only breed named after a fictional character from Sir Walter Scott's 1815 novel."},
    {"text": "Some dogs have been trained to detect pirated DVDs in customs by smelling the polycarbonate in counterfeit discs."},
    {"text": "The Thai Ridgeback is one of only three breeds with a ridge of hair growing in the opposite direction along their back."},
    {"text": "The Bergamasco Sheepdog has a unique coat made of three types of hair that naturally forms into felt-like mats called 'flocks.'", "type": "did-you-know"},
    {"text": "Dogs can be trained to detect malaria by smelling socks worn by infected individuals."},
    {"text": "The Peruvian Inca Orchid is a hairless breed considered a national treasure in Peru, depicted in pottery dating back to 750 AD."},
    {"text": "A German Shepherd named Buddy became the first seeing eye dog in America in 1928.", "month": 4, "day": 25},
    {"text": "The Kuvasz was bred by Hungarian royalty as a personal guard dog — King Matthias I trusted them more than his own guards."},
    {"text": "Dogs can count — they can tell the difference between groups of different numbers of objects.", "type": "did-you-know"},
    {"text": "The Mudi can herd up to 500 sheep with minimal direction from its handler."},
    {"text": "A Labrador Retriever named Daisy detected 551 cancer cases through scent, earning the Blue Cross Medal in 2014."},
    {"text": "The Catalburun (Turkish Pointer) is one of only three breeds with a split nose, which enhances scenting ability."},
    {"text": "Dogs typically have 42 teeth as adults — 20 on top and 22 on the bottom."},
    {"text": "The Ibizan Hound can jump up to 6 feet from a standing position and was bred to hunt rabbits on the Balearic Islands."},
    {"text": "Dogs have emotional intelligence roughly equivalent to a 2.5-year-old human child."},
    {"text": "The Otterhound is one of the most endangered native British breeds, with fewer than 1,000 worldwide.", "type": "did-you-know"},
    {"text": "The Pharaoh Hound is the national dog of Malta and one of the oldest domesticated breeds."},
    {"text": "Dogs can sense pregnancy — hormonal changes alter a woman's scent, and many dogs become more protective."},
    {"text": "The Finnish Spitz is the national dog of Finland, originally bred to bark at game birds to alert hunters."},
    {"text": "The American Foxhound was bred by George Washington, who kept a pack at Mount Vernon.", "type": "did-you-know"},
    {"text": "Dogs can smell in stereo — each nostril processes scents independently, helping determine a smell's direction."},
    {"text": "The Glen of Imaal Terrier from Ireland was bred to turn meat-roasting spits by running on a treadmill-like device."},
    {"text": "A Beagle named Elvis was trained to sniff out pregnant polar bears at the Brookfield Zoo in Chicago."},
    {"text": "The Wire Fox Terrier has won Best in Show at Westminster more than any other breed — 15 times."},
    {"text": "Dogs can detect their owner's return by the diminishing concentration of their scent in the house throughout the day.", "type": "did-you-know"},
    {"text": "The Giant Schnauzer was originally bred in Bavaria to drive cattle from farm to market."},
    {"text": "A dog's brain dedicates roughly 40% more area to analyzing smells compared to the human brain."},
    {"text": "The Sloughi, or Arabian Greyhound, has been bred by the Berber people of North Africa for thousands of years."},
    {"text": "The original Lassie movie (1943) starred a male Rough Collie named Pal — all subsequent Lassies were his descendants.", "type": "did-you-know"},
    {"text": "Dogs have a specialized brain region for processing faces and can distinguish their owner in photographs."},
    {"text": "The Cirneco dell'Etna is an ancient Sicilian breed that has hunted rabbits on Mount Etna for over 2,500 years."},
    {"text": "Dogs experience PTSD — military and police dogs can develop symptoms identical to human PTSD after traumatic events."},
    {"text": "A Bloodhound named Nick Carter tracked down over 600 criminals during his career in the early 1900s."},
    {"text": "The Treeing Walker Coonhound was bred in America to chase raccoons up trees and bark to alert hunters."},
    {"text": "The Coton de Tulear from Madagascar has a coat that feels like cotton and was once only owned by Malagasy nobility."},
    {"text": "Dogs can be taught to recognize and respond to over 1,000 different hand signals.", "type": "did-you-know"},
    {"text": "The expression 'let sleeping dogs lie' dates back to at least the 13th century and was first recorded by Chaucer."},
    {"text": "The Tosa Inu from Japan can weigh up to 200 pounds and was bred for dog fighting — today they are rare even in Japan."},
    {"text": "Dogs prefer new toys over familiar ones — a phenomenon researchers call 'neophilia.'"},
    {"text": "A dog named Swansea Jack saved 27 people from drowning in the River Tawe in Wales during the 1930s.", "type": "did-you-know"},
    {"text": "The Rat Terrier was named by President Theodore Roosevelt, who kept several at the White House."},
    {"text": "About 3.1 million dogs enter US animal shelters every year, and approximately 2 million are adopted."},
    {"text": "The Kai Ken from Japan is considered a national treasure — a rare brindle-coated breed known for loyalty."},
    {"text": "Dogs communicate through at least 10 distinct vocal sounds including barks, growls, whines, yelps, howls, and sighs."},
    {"text": "A Rough Collie named Lassie has a star on the Hollywood Walk of Fame.", "type": "did-you-know"},
    {"text": "The Petit Basset Griffon Vendéen (PBGV) is a small French hound whose name describes its entire appearance."},
    {"text": "Dogs sneeze during play to signal to other dogs that they're just playing and not being aggressive."},
    {"text": "The English Toy Spaniel was so valued by Charles II that he decreed it must be allowed in any public place, including Parliament.", "type": "did-you-know"},
    {"text": "The Black Russian Terrier was created by the Soviet military after WWII by crossing Giant Schnauzers, Rottweilers, and Airedales."},
    {"text": "Dogs have twice as many muscles in their ears as humans, giving them much greater ear movement range."},
    {"text": "The Cesky Terrier is one of the rarest breeds — there are only about 3,500 worldwide, created in Czechoslovakia in 1948."},
    {"text": "The Manchester Terrier was bred as a rat-catching champion — one named Billy reportedly killed 100 rats in under 7 minutes.", "type": "did-you-know"},
    {"text": "Studies show that petting a therapy dog before a test can reduce students' stress and improve test performance."},
    {"text": "The Norwegian Elkhound has been used for hunting moose in Scandinavia for over 6,000 years."},
    {"text": "Dogs tilt their heads when listening because their muzzles block part of their vision — tilting helps them see the speaker's face."},
    {"text": "The Spinone Italiano is one of the oldest gun dog breeds, with frescoes depicting similar dogs from 500 BC."},
    {"text": "Dogs sleeping belly-up is a sign of complete trust — it's a vulnerable position exposing vital organs."},
    {"text": "The Catahoula Leopard Dog is the state dog of Louisiana, likely bred from dogs of Native Americans and Spanish explorers.", "type": "did-you-know"},
    {"text": "Dogs can help detect low blood sugar by smelling the chemical isoprene, which rises during hypoglycemic episodes."},
    {"text": "The Hovawart is a German breed whose name means 'guardian of the estate' — protecting farms since the Middle Ages."},
    {"text": "Dogs yawn contagiously — seeing a human yawn causes many dogs to yawn, which researchers believe shows empathy."},
    {"text": "The Bedlington Terrier looks like a lamb but was bred as a fighting and hunting dog in England."},
    {"text": "The World Canine Organization (FCI) recognizes over 360 dog breeds worldwide."},
    {"text": "The Boykin Spaniel is the state dog of South Carolina, bred to hunt wild turkeys from small boats.", "type": "did-you-know"},
    {"text": "Dogs can be trained to detect invasive species — conservation dogs sniff out harmful plants and animals in national parks."},
    {"text": "The Sealyham Terrier was bred in Wales in the mid-1800s to hunt otters, foxes, and badgers."},
    {"text": "The German Wirehaired Pointer has a weather-resistant wiry coat and is the most popular hunting dog in Germany."},
    {"text": "Dogs were domesticated from wolves at least twice independently in Europe and Asia according to some genetic studies.", "type": "did-you-know"},
    {"text": "The Harrier is one of the rarest AKC breeds in America, with fewer than 200 registered annually."},
    {"text": "The Lagotto Romagnolo from Italy is the only breed specifically bred for truffle hunting.", "type": "did-you-know"},
    {"text": "A dog named Bobbie traveled 2,800 miles across America in 1923 to return to his family in Oregon after getting lost in Indiana."},
    {"text": "The Kerry Blue Terrier is born with a black coat that gradually changes to its signature blue-gray color by about 18 months."},
    {"text": "Dogs process language using the left hemisphere (for meaning) and the right hemisphere (for intonation) — similar to humans."},
    {"text": "The American Water Spaniel is the state dog of Wisconsin and one of very few breeds developed entirely in the United States."},
    {"text": "The Hungarian Puli's distinctive corded coat looks like dreadlocks and serves as protection from weather and predators."},
    {"text": "A group of Pugs is called a 'grumble.'", "type": "did-you-know"},
    {"text": "Newfoundlands have literal webbed feet — Lewis and Clark brought a Newfoundland named Seaman on their expedition."},
    {"text": "George Lucas modeled the Ewoks from Star Wars partly on his family's Alaskan Malamute."},
    {"text": "The 'shake it off' behavior dogs do after getting wet removes about 70% of the water in just 4 seconds.", "type": "did-you-know"},
    {"text": "Dogs prefer to run into the wind because it brings them more scent information about what lies ahead."},
    {"text": "The 'play bow' — front end down, back end up — is a universal invitation to play understood across all breeds."},
    {"text": "The Komondor's corded white coat was designed to help it blend in with sheep while guarding flocks from wolves."},
    {"text": "The Plott Hound is the state dog of North Carolina, bred by the Plott family for over 200 years to hunt bears.", "type": "did-you-know"},
    {"text": "Dogs can be trained to predict epileptic seizures up to 45 minutes before they occur."},
    {"text": "The Saluki can run at speeds up to 42 mph and is considered the second-fastest dog breed after the Greyhound."},
    {"text": "Dogs have approximately 319 bones in their body, compared to 206 in adult humans."},
    {"text": "A dog named Naki'o became the first dog to receive four prosthetic legs after losing his paws to frostbite.", "type": "did-you-know"},
    {"text": "The most common name for a male dog in the US is Max, while the most common female dog name is Bella."},
    {"text": "Dogs can detect bed bugs, termites, and even truffles — some truffle dogs earn their owners thousands per season."},
    {"text": "National Adopt a Shelter Dog Month is October — shelters across the US run special promotions and reduced fees."},
]

data["facts"].extend(extra)

with open(path, 'w') as f:
    json.dump(data, f, ensure_ascii=False)

print(f"Total dogs facts: {len(data['facts'])}")
