#!/usr/bin/env python3
"""Add more cat facts to reach 366+."""
import json

path = 'extension/data/facts/cats.json'
with open(path) as f:
    data = json.load(f)

extra = [
    {"text": "The Chausie is a hybrid breed created by crossing domestic cats with jungle cats (Felis chaus) — they can weigh up to 25 pounds."},
    {"text": "The Selkirk Rex has a naturally curly coat unlike any other Rex breed — it was discovered in a Montana shelter in 1987."},
    {"text": "The Snowshoe cat, known for its white paws, was developed in Philadelphia in the 1960s by crossing Siamese with American Shorthairs."},
    {"text": "The Siberian cat is Russia's national cat and is the only breed scientifically shown to produce lower levels of the allergen Fel d 1.", "type": "did-you-know"},
    {"text": "The Nebelung is a rare breed known for its long, silky blue-gray coat — its name means 'creature of the mist' in German."},
    {"text": "Munchkin cats have short legs due to a genetic mutation — they can run and jump but their shortened legs make them look like feline dachshunds.", "type": "did-you-know"},
    {"text": "The Lykoi, or 'Werewolf Cat,' naturally molts most of its fur and has a patchy coat that gives it a wolflike appearance."},
    {"text": "The Burmilla was created by accident in 1981 when a Chinchilla Persian and a Lilac Burmese mated in a UK household."},
    {"text": "The Serengeti cat was bred to look like a wild serval but contains no wild blood — it's a cross of Bengal and Oriental Shorthair."},
    {"text": "Cats' purrs have been connected to increased bone density in studies, leading NASA to study their healing properties for astronauts.", "type": "did-you-know"},
    {"text": "The average house cat's brain weighs about 30 grams — about 0.9% of its body weight, compared to 2% for humans."},
    {"text": "Cats have 244 bones at birth, but some fuse together as they grow, leaving adults with about 230 bones."},
    {"text": "A cat's kidneys are so efficient they can survive on seawater, rehydrating themselves with sea-fish prey."},
    {"text": "Cats use their tails for balance — tailless breeds like the Manx compensate with stronger hind leg muscles."},
    {"text": "The 'primordial pouch' on a cat's belly is not leftover fat from being overweight — it's a natural feature that provides protection and flexibility.", "type": "did-you-know"},
    {"text": "Cats can rotate their hind paws to face backward, allowing them to descend from trees headfirst — though many cats still get stuck."},
    {"text": "A cat named Tigger from Australia holds the record for the world's longest domestic cat whiskers at 7.5 inches."},
    {"text": "The 'blep' (a cat sticking out the tip of its tongue) is usually caused by the Flehmen response or simply forgetting to retract their tongue."},
    {"text": "Cats have dichromatic vision — they see primarily in blue and green, with limited ability to see reds and pinks."},
    {"text": "Siamese cat coloration is temperature-dependent — their fur is darker on cooler body parts (ears, face, paws, tail) due to a heat-sensitive enzyme.", "type": "did-you-know"},
    {"text": "Cats have a strong preference for running water — this instinct evolved because still water is more likely to be contaminated in the wild."},
    {"text": "The average domestic cat lives about 15 years, but many indoor cats now live to 20+ with proper veterinary care."},
    {"text": "Cats don't have a true collarbone — this gives them the flexibility to fit through any opening wider than their skull."},
    {"text": "A cat named Félicette was honored with a bronze statue in Paris in 2019, more than 50 years after her space flight.", "type": "did-you-know"},
    {"text": "Cats chirp or chatter when they see prey through a window — some researchers believe this mimics bird calls to lure prey closer."},
    {"text": "The domestic cat's closest wild relative is the African wildcat (Felis silvestris lybica), which still looks remarkably similar."},
    {"text": "Cats have a specialized 'righting mechanism' that allows them to twist their bodies mid-fall in as little as 0.3 seconds."},
    {"text": "The 'loaf position' — all four paws tucked beneath the body — indicates a relaxed but alert cat.", "type": "did-you-know"},
    {"text": "Cats have been shown to recognize their owner's voice among strangers' voices — they just don't always choose to respond."},
    {"text": "A female cat can become pregnant as young as 4 months old, which is why vets recommend early spaying."},
    {"text": "Cats can be trained — they respond to clicker training, and many can learn tricks like sit, shake, and high five."},
    {"text": "A cat's nose leather (the visible skin of the nose) has a unique pattern, much like a human fingerprint.", "type": "did-you-know"},
    {"text": "Cats mark territory through facial rubbing (bunting), scratching, urine spraying, and depositing scent from paw pads."},
    {"text": "The 'airplane ears' position (ears flattened sideways) indicates a cat is anxious, frightened, or about to become aggressive."},
    {"text": "Cats can detect illness in other cats and humans — some cats become more attentive when their owner is sick."},
    {"text": "The backward-facing barbs on a cat's tongue are called papillae — they're made of keratin, the same protein as human fingernails.", "type": "did-you-know"},
    {"text": "Cats produce about 5 different types of vocalizations: meow, purr, chirp/trill, hiss/growl, and yowl."},
    {"text": "An indoor cat's territory is typically about 200 square feet, while outdoor cats can patrol territories up to 5 square miles."},
    {"text": "The most popular cat names in America include Luna, Milo, Oliver, Bella, and Leo."},
    {"text": "Cats spend about 2/3 of their lives sleeping — a 15-year-old cat has spent about 10 years asleep."},
    {"text": "Cat allergies affect about 10% of the global population, making them one of the most common animal allergies.", "type": "did-you-know"},
    {"text": "The cost of owning a cat averages about $1,000-$1,500 per year for food, litter, veterinary care, and supplies."},
    {"text": "Cats have been domesticated for much less time than dogs — approximately 10,000 years versus 15,000-40,000 years for dogs."},
    {"text": "The sand cat (Felis margarita) is the only wild cat living primarily in true deserts and can survive without drinking water, getting moisture from prey."},
    {"text": "Cats have an exceptional memory for spatial navigation — they use a kind of mental map that remembers the layout of their territory.", "type": "did-you-know"},
    {"text": "The 'making muffins' or 'making biscuits' kneading behavior can also indicate a cat is claiming a spot as its own through scent marking."},
    {"text": "Cats can squeeze through gaps as small as their skull because their shoulders are not rigidly attached to their skeleton."},
    {"text": "The world federation of cat registries, FIFe (Fédération Internationale Féline), recognizes 48 cat breeds across four categories."},
    {"text": "Tuxedo cats have been owned by many famous people including Shakespeare, Beethoven, and Sir Isaac Newton."},
    {"text": "Cat lovers are called 'ailurophiles' — the word comes from the Greek 'ailouros' (cat) and 'philos' (lover).", "type": "did-you-know"},
    {"text": "Cats were considered sacred animals in ancient Egypt and were protected by law — exporting them was forbidden."},
    {"text": "The concept of 'cat years' is similar to 'dog years' — a 1-year-old cat is roughly equivalent to a 15-year-old human."},
    {"text": "Cats use over 30 different vocalizations to communicate with humans, but rarely vocalize with other adult cats."},
    {"text": "The 'cat's cradle' string game has been played in cultures worldwide for centuries and has no direct connection to cats."},
    {"text": "Three-colored cats (calico or tortoiseshell) have a genetic condition called X-inactivation that creates their distinctive patchy coat.", "type": "did-you-know"},
    {"text": "A cat's hearing is among the best of any mammal — they can hear sounds up to 64,000 Hz, compared to 20,000 Hz for humans."},
    {"text": "Mark Twain was a famous cat lover who once said, 'If man could be crossed with the cat, it would improve man but deteriorate the cat.'"},
    {"text": "Cats have a specialized 'death grip' reflex — when they catch prey, their back feet kick rapidly to disembowel it."},
    {"text": "The 'slow blink' between cats is called a 'cat kiss' — it's a sign of affection and trust between cats and between cats and humans.", "type": "did-you-know"},
    {"text": "Cats can survive falls from extreme heights better than moderate heights — at terminal velocity, they relax and spread out like a flying squirrel."},
    {"text": "The 'Hemingway cats' at the Ernest Hemingway Home in Key West have six or seven toes due to a polydactyl gene."},
    {"text": "A cat's stomach can only hold about 2 tablespoons of food at a time, which is why they prefer to eat small, frequent meals."},
    {"text": "Cats sometimes sleep in the 'Superman' position (front paws stretched forward, back legs stretched behind), indicating they feel extremely safe."},
    {"text": "The world's largest cat painting sold at auction was by Carl Kahler — 'My Wife's Lovers' (1893) featured 42 cats and sold for over $820,000.", "type": "did-you-know"},
    {"text": "Cats have a 'greeting stretch' where they arch their back and stretch when they see their owner — this is a sign of comfort and affection."},
    {"text": "Ancient Romans believed cats were a symbol of liberty and independence — the goddess Libertas was often depicted with a cat at her feet."},
    {"text": "Cats can develop a condition called 'pica' — compulsive eating of non-food items like wool, plastic, or rubber."},
    {"text": "The 'cat scanner' app uses AI to identify cat breeds from photos and has been downloaded millions of times.", "type": "did-you-know"},
    {"text": "Cats typically have 5 toes on their front paws and 4 on their back paws, for a total of 18 toes."},
    {"text": "The 'socialized feral cat' phenomenon shows that feral cats can become affectionate pets if socialized before 8 weeks of age."},
    {"text": "Cats can be right-eyed or left-eyed, similar to handedness in humans — they tend to favor one eye for close-up focusing."},
    {"text": "A cat's hunting success rate is about 32% for outdoor cats — significantly higher than lions (25%) but lower than African wild dogs (85%)."},
    {"text": "Florence Nightingale owned over 60 cats during her lifetime and was a passionate advocate for their welfare.", "type": "did-you-know"},
    {"text": "Cats are susceptible to 'whisker fatigue' — overstimulation of their sensitive whiskers from narrow food and water bowls."},
    {"text": "The world's first internet cat star was 'Socks,' Bill Clinton's cat, who had his own website at the White House in 1995."},
    {"text": "Cats have an average litter size of 4-6 kittens, though litters can range from 1 to 12."},
    {"text": "The 'trap-neuter-return' (TNR) method for managing feral cat populations has been shown to be more effective and humane than culling.", "type": "did-you-know"},
    {"text": "Cat whiskers are embedded three times deeper than regular hairs and are connected to the nervous system, making them incredibly sensitive."},
    {"text": "The domestic cat is technically a 'solitary social' animal — they don't need other cats but can form social groups when resources are plentiful."},
    {"text": "Cats' eyes can change from slit pupils in bright light to nearly fully dilated circles in darkness, allowing them to control light intake precisely."},
    {"text": "A cat's tail contains about 10% of all the bones in its body and is essential for balance and communication."},
    {"text": "The 'midnight crazies' in cats are caused by their crepuscular nature — they're naturally most active at dawn and dusk.", "type": "did-you-know"},
    {"text": "Cats can rotate their ears 180 degrees and point them in different directions simultaneously to locate the source of sounds."},
    {"text": "The ancient Egyptians used cats in warfare — Persian King Cambyses II reportedly used cats as shields against Egypt, knowing the Egyptians wouldn't harm them."},
    {"text": "A cat's sense of smell is about 14 times stronger than a human's."},
    {"text": "Cats can be affected by seasonal affective disorder (SAD) and become lethargic during winter months with less natural light."},
    {"text": "The 'internet cat economy' generates billions of dollars annually through merchandise, content creation, and cat-themed products.", "type": "did-you-know"},
    {"text": "Cats can learn to open doors, turn on faucets, and flush toilets through observational learning."},
    {"text": "The ancient Egyptian word for cat was 'mau,' which is also the sound a cat makes."},
    {"text": "Cats lose almost as much fluid through grooming as they do through urination due to evaporation of saliva from their coats."},
    {"text": "A cat named Nala holds the Guinness World Record for the most followers for a cat on Instagram with over 4 million."},
    {"text": "Cats evolved in desert environments, which is why they naturally conserve water and produce highly concentrated urine.", "type": "did-you-know"},
    {"text": "The phrase 'herding cats' became a popular metaphor for impossible tasks after a famous EDS Super Bowl commercial in 2000."},
    {"text": "Cats respond to silvervine (Actinidia polygama) even more strongly than catnip — about 80% of cats react to silvervine."},
    {"text": "Ship cats were so valued that Lloyd's of London once insured them, and many navies had official ship cats until the 1970s."},
    {"text": "Cats can be therapeutic for autistic children — studies show that shelter cats placed with autistic families reduced anxiety and improved social skills."},
    {"text": "The 'cat flop' — when a cat throws itself on its side at your feet — is one of the highest compliments a cat can give.", "type": "did-you-know"},
    {"text": "A cat's food preferences are largely set by 6 months of age — introducing variety early leads to less picky adult cats."},
    {"text": "Cats have been documented living on every continent except Antarctica."},
    {"text": "The 'Van pattern' — mostly white with color only on the head and tail — is named after the Turkish Van breed."},
    {"text": "Research shows indoor cats are significantly healthier and longer-lived than outdoor cats due to reduced risks from cars, predators, and disease.", "type": "did-you-know"},
    {"text": "A cat named Tama served as the stationmaster of Kishi Station in Japan from 2007 to 2015, boosting tourism revenue by an estimated $10 million."},
    {"text": "World Cat Day is celebrated differently around the world — Russia celebrates on March 1st, while the US observes National Cat Day on October 29th."},
    {"text": "Cats that live together sometimes develop a hierarchical system with a dominant 'alpha cat' that gets first access to resources."},
    {"text": "The 'airplane belly' — a cat lying on its stomach with legs splayed out like airplane wings — indicates a completely relaxed and trusting cat."},
    {"text": "Cats have photographic reflexes — they can react to visual stimuli in as little as 1/60th of a second, making them incredibly effective predators.", "type": "did-you-know"},
]

data["facts"].extend(extra)

with open(path, 'w') as f:
    json.dump(data, f, ensure_ascii=False)

print(f"Total cats facts: {len(data['facts'])}")
