#!/usr/bin/env python3
"""Add ~260 new facts to soccer.json"""
import json, os

path = os.path.join(os.path.dirname(__file__), '..', 'extension', 'data', 'facts', 'soccer.json')
with open(path) as f:
    data = json.load(f)

new_facts = [
    # === STADIUMS AROUND THE WORLD ===
    {"text": "Old Trafford, home of Manchester United since 1910, is nicknamed 'The Theatre of Dreams' — a phrase coined by Bobby Charlton."},
    {"text": "Anfield, Liverpool's home since 1892, is famous for its 'Kop' stand and the pre-match singing of 'You'll Never Walk Alone.'"},
    {"text": "The San Siro (officially Stadio Giuseppe Meazza) in Milan is shared by both AC Milan and Inter Milan and seats over 75,000."},
    {"text": "Signal Iduna Park in Dortmund has the 'Yellow Wall' (Südtribüne), the largest standing terrace in European football with 25,000 capacity.", "type": "did-you-know"},
    {"text": "The Allianz Arena in Munich can change the color of its exterior to red (Bayern), blue (1860 Munich), or white (Germany national team)."},
    {"text": "Estadio Azteca in Mexico City is the only stadium to have hosted two FIFA World Cup Finals (1970 and 1986)."},
    {"text": "La Bombonera, home of Boca Juniors in Buenos Aires, is famous for literally shaking when fans jump and chant during matches.", "type": "did-you-know"},
    {"text": "Soccer City (FNB Stadium) in Johannesburg, shaped like a traditional African pot, hosted the 2010 World Cup Final with 84,490 capacity."},
    {"text": "The Santiago Bernabéu underwent a massive €1.85 billion renovation completed in 2024, adding a retractable roof and 360-degree video screen."},
    {"text": "The Tottenham Hotspur Stadium, opened in 2019, features the world's first dividing retractable football pitch, with an NFL field underneath."},
    {"text": "Emirates Stadium became Arsenal's home in 2006 when they moved from their historic Highbury ground, increasing capacity from 38,419 to 60,704."},
    {"text": "Stamford Bridge has been Chelsea's home since 1905 and sits in the affluent Fulham area of London with a capacity of about 40,341."},
    {"text": "The Etihad Stadium became Manchester City's home in 2003, originally built for the 2002 Commonwealth Games."},
    {"text": "Estadio da Luz in Lisbon, home of Benfica, seats 64,642 and means 'Stadium of Light' — named after the parish of Luz."},
    {"text": "Celtic Park in Glasgow, known as 'Paradise,' holds 60,411 fans and is the largest football stadium in Scotland."},
    {"text": "The Johan Cruyff Arena (formerly Amsterdam Arena), home of Ajax, was one of Europe's first stadiums with a retractable roof when built in 1996."},
    {"text": "The Stadio Olimpico in Rome is shared by AS Roma and SS Lazio, creating one of Italian football's most intense shared-ground rivalries."},
    {"text": "The Stadio Diego Armando Maradona in Naples (formerly San Paolo) was renamed in 2020 after the death of Diego Maradona."},
    {"text": "Parc des Princes has been Paris Saint-Germain's home since 1974 and seats 47,929 in the 16th arrondissement of Paris."},
    {"text": "Estadio Monumental Antonio Vespucio Liberti in Buenos Aires is River Plate's home and Argentina's largest stadium at 84,567 capacity."},
    {"text": "Estadio Centenario in Montevideo, Uruguay, hosted the first-ever World Cup Final in 1930 and is a FIFA World Football Monument."},
    {"text": "The Rose Bowl in Pasadena, California, hosted the 1994 World Cup Final and the 1999 Women's World Cup Final."},
    {"text": "Lusail Stadium in Qatar, built specifically for the 2022 World Cup Final, has a golden, bowl-shaped design inspired by Arab lanterns."},
    {"text": "The Stade de France in Saint-Denis, Paris, was built for the 1998 World Cup and has a capacity of 80,698."},
    {"text": "Olympiastadion in Berlin hosted the 2006 World Cup Final between Italy and France and was originally built for the 1936 Olympics."},
    {"text": "The Millennium Stadium (Principality Stadium) in Cardiff has a retractable roof and hosted the 2017 Champions League Final."},
    {"text": "Ataturk Olympic Stadium in Istanbul hosted the legendary 2005 Champions League Final — Liverpool's 'Miracle of Istanbul' comeback."},
    {"text": "Hampden Park in Glasgow is one of the oldest football stadiums in the world, first used for football in 1903."},
    {"text": "The Metropolitano Stadium in Madrid, home of Atlético Madrid since 2017, replaced their legendary Vicente Calderón."},
    {"text": "San Mamés in Bilbao, home of Athletic Club, is called 'The Cathedral' and the club famously only signs Basque players.", "type": "did-you-know"},

    # === TEAM NAME ORIGINS, LOGOS, HISTORY ===
    {"text": "Real Madrid's 'Real' means 'Royal' in Spanish — the title was bestowed by King Alfonso XIII in 1920."},
    {"text": "FC Barcelona was founded in 1899 by Swiss businessman Joan Gamper, with the club's motto 'Més que un club' (More than a club)."},
    {"text": "Manchester United were originally called Newton Heath LYR Football Club, founded in 1878 by railway workers, renamed in 1902."},
    {"text": "Arsenal were originally called 'Royal Arsenal,' founded in 1886 by munitions workers in Woolwich, southeast London, before moving to north London in 1913.", "type": "did-you-know"},
    {"text": "Chelsea FC was founded in 1905 and named after the London borough, though the ground is actually in neighboring Fulham."},
    {"text": "Tottenham Hotspur were named after Sir Henry Percy ('Harry Hotspur'), a medieval nobleman — the cockerel on their badge represents his fighting spurs."},
    {"text": "Liverpool FC was founded in 1892 after a dispute between Everton and their Anfield landlord John Houlding, who started a new club at the ground."},
    {"text": "Juventus, meaning 'youth' in Latin, was founded by school students in Turin in 1897 — their black and white stripes were adopted in 1903."},
    {"text": "AC Milan was founded in 1899 by English expatriates, which is why the club uses the English spelling 'Milan' rather than Italian 'Milano.'", "type": "did-you-know"},
    {"text": "Inter Milan (FC Internazionale) was formed in 1908 by breakaway members of AC Milan who wanted to include international players."},
    {"text": "Bayern Munich was founded on February 27, 1900, by eleven football players led by Franz John at a restaurant in Munich."},
    {"text": "Borussia Dortmund's 'Borussia' is the Latin name for Prussia — the club was founded in 1909 by young beer drinkers at a pub.", "type": "did-you-know"},
    {"text": "Paris Saint-Germain was formed in 1970 through a merger, making it relatively young compared to other European giants."},
    {"text": "Ajax Amsterdam is named after the Greek mythological hero Ajax — their logo depicts a portrait of the warrior."},
    {"text": "Celtic FC was founded in 1887 by Irish Marist Brother Walfrid to raise funds for the poor in Glasgow's East End Irish immigrant community."},
    {"text": "Rangers FC was founded in 1872, making it one of the world's oldest football clubs, and has won a record 55 Scottish league titles."},
    {"text": "Benfica's full name is Sport Lisboa e Benfica — the eagle on their crest symbolizes independence and authority."},
    {"text": "Boca Juniors chose their colors (blue with a yellow horizontal band) from the flag of the next ship to arrive at the port of Buenos Aires — a Swedish vessel.", "type": "did-you-know"},
    {"text": "Santos FC, founded in 1912 in the port city of Santos, became world-famous as the club where Pelé played from 1956 to 1974."},
    {"text": "Flamengo is Brazil's most popular club with an estimated 40 million fans — their name comes from a neighborhood in Rio de Janeiro."},
    {"text": "Atlético Madrid's red-and-white stripes were adopted because the club's founders bought cheap mattress fabric for their shirts in the early 1900s.", "type": "did-you-know"},
    {"text": "Wolverhampton Wanderers ('Wolves') were one of England's founding football clubs and pioneers of European competition in the 1950s."},
    {"text": "Everton FC, founded in 1878, are nicknamed 'The Toffees' — possibly after a toffee shop near their original ground."},
    {"text": "West Ham United are nicknamed 'The Hammers' due to their origins as Thames Ironworks FC, founded by shipyard workers in 1895."},
    {"text": "AS Roma's badge features a she-wolf suckling Romulus and Remus, referencing the mythological founding of Rome."},
    {"text": "Napoli was founded in 1926 and play in sky blue, a color associated with the city of Naples and the Mediterranean Sea."},
    {"text": "Marseille's Olympique de Marseille (OM) is France's most popular club and the first French team to win the Champions League (1993)."},
    {"text": "Feyenoord from Rotterdam were the first Dutch club to win the European Cup in 1970, before Ajax's famous hat trick of titles."},
    {"text": "The LA Galaxy were the first major MLS club and have won a record 5 MLS Cup titles. They signed David Beckham in 2007, transforming American soccer.", "type": "did-you-know"},
    {"text": "FC St. Pauli in Hamburg is famous for its skull-and-crossbones flag and left-wing, anti-establishment fan culture unique in world football."},

    # === WORLD CUP DEEP DIVES ===
    {"text": "The 1934 World Cup in Italy was heavily influenced by Benito Mussolini, who used the tournament as political propaganda for his fascist regime.", "month": 6, "day": 10},
    {"text": "The 1938 World Cup in France was the last tournament before World War II — the competition didn't resume until 1950.", "month": 6, "day": 19},
    {"text": "The 1954 World Cup featured the 'Miracle of Berne' — West Germany defeated heavily favored Hungary 3-2 in the final despite Hungary being unbeaten for four years.", "month": 7, "day": 4},
    {"text": "The 1958 World Cup in Sweden saw a 17-year-old Pelé burst onto the world stage, scoring six goals including two in the final.", "month": 6, "day": 29},
    {"text": "The 1962 World Cup in Chile featured the 'Battle of Santiago,' a notoriously violent match between Chile and Italy that required police intervention."},
    {"text": "The 1966 World Cup Final — England 4, West Germany 2 — featured Geoff Hurst's controversial third goal and Kenneth Wolstenholme's iconic commentary: 'They think it's all over... it is now!'", "month": 7, "day": 30},
    {"text": "The 1970 World Cup in Mexico is considered the greatest tournament ever, with Brazil's legendary team playing the most beautiful football in World Cup history.", "month": 6, "day": 21},
    {"text": "The 1974 World Cup introduced the Netherlands' 'Total Football' philosophy to the world, though they lost the final to West Germany.", "month": 7, "day": 7},
    {"text": "The 1978 World Cup in Argentina was controversial due to the military dictatorship — the tournament was surrounded by political tension and allegations of match-fixing."},
    {"text": "The 1982 World Cup in Spain featured Paolo Rossi's incredible comeback from a match-fixing ban to lead Italy to victory with six goals.", "month": 7, "day": 11},
    {"text": "The 1986 World Cup was moved from Colombia to Mexico due to financial difficulties — it became Maradona's tournament with his two iconic goals against England.", "month": 6, "day": 29},
    {"text": "The 1990 World Cup in Italy was famously defensive and low-scoring, with Cameroon's shock opening-day defeat of defending champions Argentina.", "month": 7, "day": 8},
    {"text": "The 1994 World Cup in the USA saw Roberto Baggio miss the decisive penalty in the final, sending Brazil to their fourth World Cup title.", "month": 7, "day": 17},
    {"text": "The 1998 World Cup in France featured host nation France winning their first World Cup, led by Zinedine Zidane's two goals in the final.", "month": 7, "day": 12},
    {"text": "The 2002 World Cup, co-hosted by South Korea and Japan, was the first in Asia and featured stunning upsets — South Korea reached the semifinals.", "month": 6, "day": 30},
    {"text": "The 2006 World Cup in Germany is remembered for the dramatic final between Italy and France, ended by Zidane's headbutt on Materazzi and Italy winning on penalties.", "month": 7, "day": 9},
    {"text": "The 2010 World Cup in South Africa was the first on African soil - famous for the vuvuzela horns, Paul the Octopus, and Spain winning their first-ever World Cup.", "month": 7, "day": 11},
    {"text": "The 2014 World Cup in Brazil featured Germany's astonishing 7-1 demolition of hosts Brazil in the semifinal — known as the 'Mineirazo.'", "month": 7, "day": 8},
    {"text": "The 2018 World Cup in Russia saw France win their second title, with Mbappé (19) becoming the youngest player since Pelé to score in a final.", "month": 7, "day": 15},
    {"text": "The 2022 World Cup Final between Argentina and France is considered the greatest final ever — Messi and Mbappé each scored twice before Argentina won on penalties.", "month": 12, "day": 18},
    {"text": "The FIFA World Cup trophy is made of 18-carat gold, weighs 13.61 pounds, and depicts two human figures holding up the Earth."},
    {"text": "The original World Cup trophy, the Jules Rimet Trophy, was permanently awarded to Brazil after their third win in 1970 and was stolen in 1983, never recovered."},
    {"text": "Miroslav Klose holds the all-time World Cup scoring record with 16 goals across four tournaments (2002-2014) for Germany."},

    # === PLAYER BIOS — ALL-TIME LEGENDS ===
    {"text": "Franz Beckenbauer, 'Der Kaiser,' revolutionized the sweeper position and is the only person to win the World Cup as both captain (1974) and manager (1990)."},
    {"text": "Eusébio, the 'Black Panther' from Mozambique, scored 733 goals in 745 matches for Benfica and Portugal and was the 1966 World Cup's top scorer with 9 goals.", "type": "did-you-know"},
    {"text": "Garrincha, nicknamed 'The Joy of the People,' had legs of different lengths due to childhood polio but became one of Brazil's greatest ever wingers."},
    {"text": "Zico, known as the 'White Pelé,' scored 52 goals in 71 appearances for Brazil and is considered one of the greatest playmakers in football history."},
    {"text": "Michel Platini scored a stunning 9 goals in 5 games at Euro 1984, leading France to the European Championship — a tournament record that still stands."},
    {"text": "Bobby Charlton survived the 1958 Munich air disaster that killed 8 Manchester United players and went on to lead England to their only World Cup in 1966.", "type": "did-you-know"},
    {"text": "Ferenc Puskás scored 84 goals in 85 international matches for Hungary and later scored 242 goals in 262 matches for Real Madrid."},
    {"text": "Marco van Basten's volleyed goal in the 1988 European Championship Final is widely considered the greatest goal in tournament history.", "month": 6, "day": 25},
    {"text": "Ruud Gullit helped define the great AC Milan side of the late 1980s and was one of the first major Black European superstars in football."},
    {"text": "Franco Baresi spent his entire 20-year career (1977-1997) at AC Milan and is considered one of the greatest defenders in football history — Milan retired his number 6."},
    {"text": "Roberto Baggio, 'The Divine Ponytail,' won the 1993 Ballon d'Or and is remembered for both his brilliance and his tragic penalty miss in the 1994 World Cup Final."},
    {"text": "Rivaldo won the Ballon d'Or in 1999 and scored a famous overhead kick hat-trick goal against Valencia in 2001 to keep Barcelona in the Champions League."},
    {"text": "Romário scored over 1,000 career goals and was the 1994 World Cup's best player — his clinical finishing helped Brazil win their fourth title."},
    {"text": "Cafu is the only player to appear in three consecutive World Cup Finals (1994, 1998, 2002), winning twice with Brazil."},
    {"text": "Raúl scored 323 goals for Real Madrid over 16 seasons and was the Champions League's all-time top scorer until Messi and Ronaldo surpassed him."},
    {"text": "Samuel Eto'o won three Champions League titles (two with Barcelona, one with Inter Milan) and is considered the greatest African player in Champions League history."},
    {"text": "Andriy Shevchenko won the 2004 Ballon d'Or after scoring 175 goals in 296 appearances for AC Milan, becoming Ukraine's greatest-ever footballer."},
    {"text": "Alessandro Del Piero scored 290 goals in 705 appearances for Juventus, becoming their all-time leading scorer and a club legend."},
    {"text": "Pavel Nedvěd's tireless energy and powerful left foot earned him the 2003 Ballon d'Or while playing for Juventus."},
    {"text": "Luís Figo's controversial transfer from Barcelona to Real Madrid in 2000 for a world-record fee made him one of football's most polarizing figures."},
    {"text": "Sócrates was a Brazilian midfielder who was also a medical doctor — he captained the legendary 1982 Brazil World Cup team and was a political activist.", "type": "did-you-know"},
    {"text": "Lothar Matthäus holds the record for most World Cup appearances (25 matches across five tournaments) and won the first FIFA World Player of the Year in 1991."},
    {"text": "George Weah is the only African player to win the Ballon d'Or (1995) and later became the President of Liberia in 2018.", "type": "did-you-know"},
    {"text": "Davor Šuker won the Golden Boot at the 1998 World Cup with 6 goals for Croatia in their first-ever World Cup appearance as an independent nation."},
    {"text": "Hristo Stoichkov, the Bulgarian star, won the 1994 Ballon d'Or after leading Bulgaria to an improbable World Cup semifinal."},
    {"text": "Dino Zoff remains the oldest player to win a World Cup — he captained Italy to victory at age 40 in 1982.", "type": "did-you-know"},
    {"text": "Gordon Banks' save from Pelé's header in the 1970 World Cup is widely regarded as the greatest save in football history."},
    {"text": "Kenny Dalglish is the only player to score over 100 goals in both English and Scottish top-flight football (Liverpool and Celtic)."},
    {"text": "Eric Cantona's kung-fu kick on a Crystal Palace fan in 1995 led to a nine-month ban, but he returned to lead Manchester United to the title."},
    {"text": "Just Fontaine's 13 goals at the 1958 World Cup set an all-time record for a single tournament that has never been remotely threatened."},
    {"text": "Hungarian great Sándor Kocsis scored 75 goals in 68 internationals and had an astounding 11 goals at the 1954 World Cup."},
    {"text": "Bobby Moore captained England to their 1966 World Cup victory and is considered the finest English defender of all time — a statue stands at Wembley.", "month": 7, "day": 30},
    {"text": "Stanley Matthews, the 'Wizard of Dribble,' won the first-ever Ballon d'Or in 1956 at age 41 — the oldest recipient in history.", "type": "did-you-know"},
    {"text": "Dennis Law is the only Scottish footballer to win the Ballon d'Or (1964) and remains one of Manchester United's greatest-ever strikers."},
    {"text": "Raymond Kopa, the French-Polish forward, won three consecutive European Cups with Real Madrid and the 1958 Ballon d'Or."},
    {"text": "Omar Sívori won the 1961 Ballon d'Or playing for Juventus — born in Argentina, he also represented Italy internationally."},
    {"text": "Giacinto Facchetti revolutionized the fullback position in the 1960s, scoring 75 goals from defense for Inter Milan — extraordinary for a defender.", "type": "did-you-know"},
    {"text": "Gianfranco Zola, Chelsea's greatest foreign player, won the FWA Footballer of the Year in 1997 and had a statue erected outside Stamford Bridge."},
    {"text": "David Beckham popularized soccer in America and became one of sport's biggest global brands — his free kicks and crossing ability were unmatched."},
    {"text": "Ronaldo 'Il Fenomeno' (R9) won the World Cup twice (1994, 2002), two Ballon d'Ors, and is regarded as one of the greatest pure strikers ever."},

    # === PLAYER BIOS — TOP CURRENT PLAYERS ===
    {"text": "Vinícius Júnior has become Real Madrid's most dangerous attacker, winning the Champions League in 2024 and finishing as a top Ballon d'Or contender."},
    {"text": "Pedri, Barcelona's young Spanish midfielder, has been compared to Andrés Iniesta for his vision, composure, and ability to dictate play."},
    {"text": "Gavi became the youngest-ever Kopa Trophy winner in 2022, awarded to the best player under 21."},
    {"text": "Bukayo Saka has become Arsenal's most important player, named the club's Player of the Season multiple times and a key England international."},
    {"text": "Phil Foden, a product of Manchester City's academy, won the PFA Young Player of the Year multiple times and became England's next great creative talent."},
    {"text": "Cole Palmer emerged as Chelsea's star player after leaving Manchester City, winning the PFA Young Player of the Year in 2024."},
    {"text": "Lamine Yamal became the youngest player ever to play and score at a European Championship at 16, starring for Spain at Euro 2024.", "type": "did-you-know"},
    {"text": "Florian Wirtz of Bayer Leverkusen has been hailed as Germany's most talented young prospect, helping Leverkusen win an unbeaten Bundesliga title in 2024."},
    {"text": "Victor Osimhen's 26 Serie A goals in 2022-23 fired Napoli to their first Scudetto in 33 years, ending their long wait since the Maradona era."},
    {"text": "Rodri won the 2024 Ballon d'Or after a stellar season with Manchester City and a decisive performance for Spain at Euro 2024."},
    {"text": "Alisson Becker is widely regarded as the best goalkeeper in the world, transforming Liverpool's defense after joining from Roma in 2018."},
    {"text": "Thibaut Courtois made a stunning return from injury to star for Real Madrid, having made match-winning saves in the 2022 Champions League Final."},
    {"text": "Harry Kane left Tottenham for Bayern Munich in 2023, quickly becoming the Bundesliga's most prolific foreign scorer."},
    {"text": "Declan Rice's £105 million transfer from West Ham to Arsenal in 2023 made him the most expensive British player of all time."},
    {"text": "Federico Valverde has become one of the world's most complete midfielders at Real Madrid, combining technique, power, and tireless running."},
    {"text": "Rafael Leão's explosive pace and dribbling at AC Milan have made the Portuguese winger one of Serie A's most exciting players."},
    {"text": "Martin Ødegaard captains Arsenal despite being just 25, having fulfilled the promise that saw Real Madrid sign him at age 16.", "type": "did-you-know"},
    {"text": "Jamal Musiala chose to represent Germany over England and has become Bayern Munich's most creative force and one of football's brightest young talents."},
    {"text": "Aurélien Tchouaméni anchors Real Madrid's midfield and is considered France's long-term successor to the holding midfielder role."},
    {"text": "Enzo Fernández won the 2022 World Cup Young Player award with Argentina and then joined Chelsea for a British-record £106.8 million."},
    {"text": "William Saliba's partnership with Gabriel at Arsenal's center-back formed one of the best defensive duos in Premier League history."},
    {"text": "Alejandro Garnacho has emerged as an exciting young talent at Manchester United, with his overhead kick goal winning multiple awards."},

    # === CLUB HISTORIES, GREAT TEAMS ===
    {"text": "Real Madrid have won a record 15 Champions League/European Cup titles — more than any other club — including six in the 21st century alone."},
    {"text": "Barcelona's 2009 team under Pep Guardiola won an unprecedented six trophies in a single calendar year (the Sextuple).", "type": "did-you-know"},
    {"text": "Bayern Munich have won over 30 Bundesliga titles and 6 European Cups/Champions League trophies, dominating German football for decades."},
    {"text": "Juventus have won a record 36 Serie A titles and are Italy's most successful club, earning the nickname 'La Vecchia Signora' (The Old Lady)."},
    {"text": "Liverpool's five European Cup/Champions League victories include the improbable 2005 comeback and their dominant 2019 squad under Jürgen Klopp."},
    {"text": "Manchester United's 'Class of '92' — Beckham, Giggs, Scholes, Neville brothers, and Butt — emerged from the academy to form a dynasty under Sir Alex Ferguson."},
    {"text": "Manchester City were a mid-table club before their 2008 takeover by Abu Dhabi's Sheikh Mansour transformed them into serial Premier League winners."},
    {"text": "Chelsea's modern era began with Roman Abramovich's purchase in 2003, financing an era that produced 5 Premier League titles and 2 Champions League wins."},
    {"text": "Ajax's legendary 1970s team won three consecutive European Cups (1971-73) and produced Cruyff, Neeskens, and Rep."},
    {"text": "Benfica won back-to-back European Cups in 1961 and 1962 with Eusébio, establishing themselves as one of Portugal's greatest clubs."},
    {"text": "Porto defied the odds to win the 2004 Champions League under José Mourinho, launching his career as one of football's most famous managers."},
    {"text": "The Old Firm derby between Celtic and Rangers in Glasgow is one of the most intense rivalries in world football, rooted in religious and cultural divisions."},
    {"text": "Nottingham Forest won back-to-back European Cups in 1979 and 1980 under Brian Clough, having been promoted from the Second Division just two years earlier.", "type": "did-you-know"},
    {"text": "Red Star Belgrade won the 1991 European Cup, becoming the only Serbian club to win Europe's top prize."},
    {"text": "Steaua Bucharest (now FCSB) won the 1986 European Cup, making them the first Eastern European club to win the tournament."},
    {"text": "Club América is Mexico's most successful and controversial club with 13 Liga MX titles, beloved and hated in equal measure across Mexico."},
    {"text": "River Plate and Boca Juniors' rivalry — the Superclásico — divides Argentina along class lines: River represents the upper class, Boca the working class.", "type": "did-you-know"},
    {"text": "Al-Hilal and Al-Ahli in Saudi Arabia have become global talking points after signing stars like Neymar, Benzema, and other European superstars."},

    # === INTERNATIONAL TOURNAMENTS ===
    {"text": "The European Championship (Euros) has been held since 1960 — Germany and Spain are tied for the most wins with 3 titles each."},
    {"text": "Greece's Euro 2004 victory is considered the greatest upset in European Championship history — they were 150-1 outsiders.", "type": "did-you-know"},
    {"text": "Denmark won Euro 1992 despite not originally qualifying — they replaced Yugoslavia (banned due to civil war) and stunned the continent.", "month": 6, "day": 26},
    {"text": "The Africa Cup of Nations (AFCON) is the continent's premier tournament, first held in 1957 with only three teams — Egypt, Sudan, and Ethiopia."},
    {"text": "Egypt has won the Africa Cup of Nations a record 7 times, while Cameroon (5 titles) are known as the 'Indomitable Lions.'"},
    {"text": "The Copa Libertadores is South America's equivalent of the Champions League — Independiente of Argentina have won it a record 7 times."},
    {"text": "The Asian Cup, first held in 1956, has seen Japan win 4 times — the most of any nation in the competition."},
    {"text": "The CONCACAF Gold Cup is the top national team tournament for North America, Central America, and the Caribbean — Mexico leads with 12 wins."},
    {"text": "The FIFA Club World Cup expanded from 7 teams to 32 teams in 2025, creating a month-long tournament modeled after the World Cup."},
    {"text": "The Women's European Championship (Women's Euros) saw England win the 2022 tournament on home soil before 87,192 fans at Wembley.", "month": 7, "day": 31},

    # === WOMEN'S SOCCER ===
    {"text": "The NWSL (National Women's Soccer League) in the USA has grown rapidly since its 2013 founding, attracting record crowds and major investment."},
    {"text": "Ada Hegerberg of Norway won the first-ever Women's Ballon d'Or in 2018 and is the all-time Champions League top scorer.", "type": "did-you-know"},
    {"text": "Mia Hamm scored 158 international goals for the USWNT and was the face of women's soccer worldwide in the 1990s and early 2000s."},
    {"text": "Christine Sinclair retired as the all-time leading international scorer (men's or women's) with 190 goals for Canada."},
    {"text": "Alex Popp, Germany's veteran striker, has been a symbol of German women's football for over a decade."},
    {"text": "The 1999 Women's World Cup Final at the Rose Bowl drew 90,185 fans — a record for any women's sporting event at the time.", "month": 7, "day": 10},
    {"text": "Brandi Chastain's penalty kick and iconic jersey celebration in the 1999 Women's World Cup Final became one of the most famous images in sports.", "month": 7, "day": 10},
    {"text": "Spain won their first-ever Women's World Cup in 2023, defeating England 1-0 in the final in Sydney, Australia.", "month": 8, "day": 20},
    {"text": "Aitana Bonmatí won both the Women's Ballon d'Or and the Golden Ball at the 2023 Women's World Cup, establishing herself as the best player in the world."},
    {"text": "Title IX in the United States (1972) dramatically increased women's participation in sports and is a major reason the US dominates women's soccer.", "type": "did-you-know"},

    # === RULES, CULTURE, MISCELLANEOUS ===
    {"text": "The 'Centurion' season — when a team reaches 100 points — was first achieved in a major European league by Manchester City in the 2017-18 Premier League."},
    {"text": "The World Cup trophy cannot be permanently kept by any nation — the current trophy was introduced in 1974 and remains FIFA's property."},
    {"text": "Soccer is called 'football' in most of the world — the word 'soccer' originated in England as slang for 'association football' in the 1880s.", "type": "did-you-know"},
    {"text": "A 'Cap' in international football refers to an appearance — the term comes from the tradition of giving players a physical cap for each game."},
    {"text": "The 'Aguero moment' in 2012 — Manchester City's last-second title win — has been replayed more than any other Premier League moment.", "month": 5, "day": 13},
    {"text": "The 'Double' (league and cup in one season) was first achieved in England by Preston North End in the 1888-89 season."},
    {"text": "The 'Quadruple' — winning league, Champions League, FA Cup, and League Cup in one season — has never been achieved by an English club."},
    {"text": "The Puskas Award for best goal of the year was first given in 2009 — Cristiano Ronaldo won the inaugural award for a goal against Porto."},
    {"text": "Soccer's 'Laws of the Game' are maintained by the International Football Association Board (IFAB), which has existed since 1886."},
    {"text": "The 'Wall' in free kicks must stand at least 9.15 meters (10 yards) from the ball."},
    {"text": "The penalty spot is exactly 12 yards (11 meters) from the goal line, a distance that has remained unchanged since 1891."},
    {"text": "Extra time (two 15-minute halves) and penalty shootouts were first used at the 1970 World Cup to decide knockout matches."},
    {"text": "The 'Advantage Rule' allows the referee to let play continue after a foul if the team in possession would benefit more from continuing than receiving a free kick."},
    {"text": "Substitutions were first allowed in the World Cup in 1970 — originally only two per match, now five are permitted following COVID-era rule changes."},
    {"text": "The FIFA World Rankings, introduced in 1992, determine tournament seedings and are updated monthly based on match results."},
    {"text": "VAR (Video Assistant Referee) reviews four types of decisions: goals, penalties, direct red cards, and mistaken identity."},
    {"text": "The longest unbeaten run in international football belongs to Brazil, who went 35 games without defeat from 1993 to 1996."},
    {"text": "In professional soccer, the pitch can legally be any length between 100-110 meters and any width between 64-75 meters."},
    {"text": "The 'Diagonal System of Control' is the standard method of referee positioning, with the referee running diagonally across the pitch."},
    {"text": "The '12th Man' refers to a team's fans — Fenerbahçe's supporters once generated 131.76 decibels, a Guinness World Record for stadium noise.", "type": "did-you-know"},
    {"text": "Transfer deadline day has become a media spectacle in England, with live coverage outside training grounds as clubs rush to complete deals."},
    {"text": "The Premier League's international broadcast rights were worth over £5 billion for the 2022-25 cycle, making it the richest league in the world."},
    {"text": "Soccer balls were originally made from inflated pig bladders wrapped in leather — modern balls use synthetic materials and are precisely manufactured."},
    {"text": "The 'Ballon d'Or' ceremony is held annually in Paris at the Théâtre du Châtelet, organized by France Football magazine."},
    {"text": "The first ever floodlit football match was played at Bramall Lane, Sheffield, in 1878 using lights powered by dynamos.", "type": "did-you-know"},
    {"text": "The 'Inverted Fullback' position, popularized by Pep Guardiola at Manchester City, sees fullbacks tuck inside to form a midfield double pivot."},
    {"text": "Saudi Arabia's shock 2-1 victory over Argentina in the 2022 World Cup group stage is one of the greatest upsets in World Cup history.", "month": 11, "day": 22},
    {"text": "Senegal's 1-0 upset of defending champions France in the opening match of the 2002 World Cup stunned the football world.", "month": 5, "day": 31},
    {"text": "North Korea shocked Italy 1-0 at the 1966 World Cup, one of the biggest upsets in tournament history."},
    {"text": "The USA shocked England 1-0 at the 1950 World Cup in Brazil, one of the most unlikely results in football history — most American players were amateurs.", "type": "did-you-know"},
]

data["facts"].extend(new_facts)

with open(path, 'w') as f:
    json.dump(data, f, ensure_ascii=False)

print(f"Total facts now: {len(data['facts'])}")
